### ISSUE TITLE
Write a Node program that runs input files through our pipeline

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#1003]
This allows us to re-use our pipelines and run them separately, in Jupyter Notebooks, for instance.

**Comment by pdehaye** [comment]
This solely concerns the pipelines, not the visualizations?

**Comment by valentinoli** [comment]
> This solely concerns the pipelines, not the visualizations?

Yes.

**Comment by alexbfree** [comment]
originally comes from @andreaskundig' idea. He is currently working on first part of this, using file manager from Node.

**Comment by valentinoli** [comment]
Working on the Node script today

**Comment by alexbfree** [comment]
@valentinoli reports this is progressing well

**Comment by alexbfree** [comment]
@pdehaye highlevel observation: we should work more on improving research pipelines than educational aspect for now.

**Comment by alexbfree** [comment]
@alexbfree could help with this if useful

**Comment by alexbfree** [comment]
moving to Specs done until bizdev push it back to dev, dependent on priority

**Comment by valentinoli** [comment]
https://www.npmjs.com/package/@hestia.ai/hestias-hearth

**Comment by valentinoli** [comment]
Closing as the main functionalities have been implemented and the package is published. Tests are also working and the PR has been merged, which included changes in the packages structure and republishing of all packages to their first major semantic version 1.0.0
