### ISSUE TITLE
put vega graphs configuration in the right place

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#103]
It should be a json in **experiences/tinder/examples/main/visualizations.json**, rather than in **experiences/tinder/tinder.json**

The graph specs themselves should be json files, not files with the ".vega" extension that exists only in this project"

**Comment by andreaskundig** [comment]
This becomes irrelevant with #193

**Comment by valentinoli** [comment]
I think also we need to think about how to organize the viz declarations on the monorepo
