### ISSUE TITLE
Feature request - Change the header of Digipower.Academy

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#1030]
Change the header of the digipower.academy website for it to look like that (with the good font and the good purple):
![Image](https://user-images.githubusercontent.com/81250365/193554889-024f55cb-0768-42cb-a2d5-cc67ded77bc2.png)

Move Tim Berners-Lee's quote in the footer, under "The Digipower.academy has emerged out of projects initiated separately by [SITRA ](https://www.sitra.fi/en/projects/digipower-investigation), [Migros Pioneer Fund ](https://www.migros-engagement.ch/en/news-projects/technology-ethics/hestialabs)(via [the HestiaLabs project ](http://www.hestialabs.org/)) and [PersonalData.IO](https://personaldata.io/)", same color, same font size as this text, italic for what's between quotation marks: "_We need to train both the people who are putting data and information out there, as well as those reading it, how to interpret and question it to ensure they understand it and are not being misled or deceived._" - Sir Tim Berners-Lee, inventor of the World Wide Web

**Comment by alexbfree** [comment]
discussed with Charles, this is needed before Thursday, I said we (dev) will make sure it gets done on Wednesday.
