### ISSUE TITLE
🐞 [BUG]: Import statement bug (blocking deployments)

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The import statement that loads packages in [experiences/store/index.js](https://github.com/hestiaAI/hestialabs-experiences/blob/1defbfb1169f8c6dc3520529b88da18aa6ca7ae8/experiences/store/index.js#L177) throws an error.

### Expected Behavior

It should not throw an error and work as it has previously

### Steps to Reproduce

Go to test.hestialabs.org. The page doesn't display. Look at the browser console.

### Web Sites

test.hestialabs.org

### Browser

Vivaldi

### Log Output and Error Messages

```shell
Error: Module parse failed: Unexpected token (225:31)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| }, function () {
|   var A;
>   if ("string" == typeof import.meta.url && (A = import.meta.url), !A) throw new Error("Automatic publicPath is not supported in this browser");
|   A = A.replace(/#.*$/, "").replace(/\?.*$/, "").replace(/\/[^\/]+$/, "/"), t.p = A + "../../";
| }();
    at 912 (4f08bfc.js:1:84)
    at n (a838af9.js:1:578)
    at n.t (a838af9.js:1:4354)
    at 5b97c22.js:1:43668
    at async Promise.all (/index 1)
```

**Comment by valentinoli** [comment]
Now test.hestialabs.org is working. I built the app on the master branch, and then copied it to netlify-test. I don't know if anything I did solved the bug or not.

**Comment by alexbfree** [comment]
Closing but we will re-open it if the bug re-appears
