### ISSUE TITLE
🐞 [BUG] remove username for participant bubble before upload

### ISSUE THREAD

**Issue by pdehaye** [hestiaAI/hestialabs-experiences#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When about to upload in a participant bubble, users are asked for a username and a password. This is a mistake (see also [here](https://github.com/hestiaAI/clients/issues/53#issuecomment-1274680012)). 

### Expected Behavior

They should at most be asked for a *codeword*. Better to use the language *codeword* because the passwords we choose are too weak. 

It is worth however discussing what other options there are:
- captcha
- access control based on some authentication mechanism more or less related to the aggregator

### Steps to Reproduce

1. go to participant
2. attempt to "Share My Data"
3. you are asked for username and password

### Web Sites

digipower.academy

### Browser

All

**Comment by valentinoli** [comment]
I could not reproduce this, a screenshot would be useful

**Comment by pdehaye** [comment]
Sorry, I was mistaken.

**Comment by valentinoli** [comment]
@pdehaye 
We should still replace password with codeword --> feature request?

**Comment by pdehaye** [comment]
yes
