### ISSUE TITLE
Migrate packages to npm

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#1076]
In order to distribute our modules through cdns like unpkg, we can publish them on npm.

I have a working example for the kepler-iframe subproject, [temporarily published to my own npm account](https://www.npmjs.com/package/@andreaskundig/kepler-iframe).

See [Creating an organization](https://docs.npmjs.com/creating-an-organization) in npm's documentation.

**Comment by pdehaye** [comment]
I have created the organization: https://www.npmjs.com/org/hestia.ai
I see it referred to as `@hestia.ai`
I have invited @andreaskundig there, but don't know if I should invite others (usernames?).
I put this is dev review.

**Comment by andreaskundig** [comment]
It works!

[hestia.ai](http://hestia.ai/) has its first package on npm 🎉
https://www.npmjs.com/package/@hestia.ai/kepler-iframe

Anyone who want to publish packages needs to create an npm user with two factor authentication, whom @pdehaye  then needs to add to the [hestia.ai](http://hestia.ai/) npm organisation

**Comment by alexbfree** [comment]
I was just going through Testing (Dev) and noticed this one - seems like this is Done and could be closed? Good job guys!

**Comment by valentinoli** [comment]
Awaiting Paul's invitation to the npm organization

**Comment by fquellec** [comment]
Waiting for a modification test.
