### ISSUE TITLE
🐞 [BUG]: Routing bug, cannot access experience within a bubble with URL

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to access an experience within a bubble directly using it's URL, we get an infinite spinner, it seems to be related to a redundant navigation ?  
We can still access experiences within a bubble by using the UI.

### Expected Behavior

We should be able access any bubble experience from an URL directly, allowing easy sharing and linking to bubble experience on the home page. 

### Images

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/17878016/195565664-e31b4084-08d0-4617-8568-7cedec8f25ac.png">

### Steps to Reproduce

1. Copy this URL in your browser: https://digipower.academy/bubble/demo-participant/experience/twitter

### Web Sites

localhost (master branch), digipower.academy, test.hestialabs.org, experiences.hestialabs.org

### Browser

Chromium

### Operating System

macOS

### Log Output and Error Messages

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/17878016/195565774-1ddd86bd-1154-4180-9cfb-e5674d82deb7.png">

**Comment by alexbfree** [comment]
I noticed something similar (macOS Mojave, Brave browser):

For me, 

https://digipower.academy/bubble/live-participant spins forever and doesn't load

https://digipower.academy/bubble/live-participant?redirect=%2Fbubble%2Flive-participant (which is where you end up from clicking login) works, and changes the addressbar to https://digipower.academy/bubble/live-participant, and the experience loads.

But if you reload page, or go to https://digipower.academy/bubble/live-participant directly, it doesn't load.

**Comment by valentinoli** [comment]
Should be fixed in parallel with #1101

**Comment by valentinoli** [comment]
Will be fixed with #1064

**Comment by alexbfree** [comment]
@valentinoli reports this is fixed.
