### ISSUE TITLE
[UMBRELLA] Improvements to Kepler UI and Uber experiences based on TL feedback

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1087]
[UPDATED]

Things that @Shalf is aware of:

- Zoom in / zoom out - difficult with trackpad (maybe add +/- buttons?) -> https://github.com/hestiaAI/hestialabs-experiences/issues/1092
- can we do anything about lag - spinners etc, wastes time in demos (i think not, it's inherent to the architectural choices we have made)
- cache issue -> https://github.com/hestiaAI/hestialabs-experiences/issues/1091

Things Alex was aware of:

- green lines accessibility issue => https://github.com/hestiaAI/hestialabs-experiences/issues/1041

Other issues Alex found for Uber drivers:

- tabs not loading correctly:
  - https://github.com/hestiaAI/hestialabs-experiences/issues/1088
  - https://github.com/hestiaAI/hestialabs-experiences/issues/1089 
  - https://github.com/hestiaAI/hestialabs-experiences/issues/1090 
  - https://github.com/hestiaAI/hestialabs-experiences/issues/1097
  
New issues raised after talking to Paul:

- ~https://github.com/hestiaAI/hestialabs-experiences/issues/1093~ [Removed from this umbrella ticket as it is not vital for Uber/Thursday digipowerlive, now more focused on Google]
- https://github.com/hestiaAI/hestialabs-experiences/issues/1094
- https://github.com/hestiaAI/hestialabs-experiences/issues/1095
- https://github.com/hestiaAI/hestialabs-experiences/issues/1096
  

Original text : 

From Paul 
> Next week Thursday in the morning will be digipowerlive for Uber driver and passenger, in French. Kepler UI absolutely needs to be improved based on UI feedback from yesterday TL session (ask Shalf). Today-urgent given holidays next week.

**Comment by alexbfree** [comment]
@Shalf Please could you add more details here about what is needed?

**Comment by Shalf** [comment]
I only mentionned UX in the context of the homepage yesterday. At this point, I've never seen or used our Uber interface. Can we start with that?
Is 11.30am CEST (Lausanne time) a good time to test that together please @alexbfree? I can't precise PO's needs I don't know of, though.

**Comment by fquellec** [comment]
@alexbfree to get the requirements from bizdev

**Comment by alexbfree** [comment]
I am meeting @Shalf to find out more, but @pdehaye sounds like additional input from you will still be needed to make sure we do capture what you are raising

**Comment by alexbfree** [comment]
Taking notes in call with @Shalf :

(we are going through TL google experience)

- Zoom in / zoom out - difficult with trackpad (maybe add +/- buttons or drag rect to zoom?)
- 
-

**Comment by alexbfree** [comment]
@pdehaye please review the links in [here](https://github.com/hestiaAI/hestialabs-experiences/issues/1087#issuecomment-1278756686) and add anything you are aware of that we haven't captured. Plus feel free to give any indication on priorities amongst these issues

**Comment by pdehaye** [comment]
First and last definitely high priorities. Needs finer decisions.

**Comment by alexbfree** [comment]
ok i can do some additional testing in french

**Comment by alexbfree** [comment]
Additional feedback from Paul:
- Whitespace issues on large screens (2 separate issues)
- Issues with default zoom level on kepler maps
- need to do some French testing

**Comment by alexbfree** [comment]
#1091 and #1092 remain, but this umbrella ticket is no longer needed. closing.
