### ISSUE TITLE
Hide Bubble Icons Behind A Login

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1101]
Arising from Paul's ticket hestiaAI/clients/issues/25, the plan is that no bubble icons should be listed on the frontpage of digipower.academy (or in left nav) by default. Instead, we have a Login feature.

The user can log in by entering their bubble's ID, and the codeword they have.

Once the login has been successful, the appropriate bubble(s) are now accessible in the left nav and on the front page where applicable.

There should also be a log out button, at which point these icons disappear.

Icons for individual experiences are unaffected.

**Comment by alexbfree** [comment]
Dev to produce a wireframe or sketch or plan, and get it reviewed by bizdev before proceeding.

**Comment by fquellec** [comment]
This is waiting for #896 to be done

**Comment by valentinoli** [comment]
Potential icon for representing data spaces

![image](https://user-images.githubusercontent.com/23453691/199685833-119ae594-d4a4-4362-938d-2690d8629b18.png)


The icon could be displayed in the app bar and clicking it would take the user to a page with a list of available data spaces. Selecting a data space takes you to the data space home page. No authentication with a codeword is required until the user accesses an experience that requires a codeword. The idea is that no session is maintained, so if the user refreshes the browser he needs to log in again. No log out functionality is needed.

**Comment by valentinoli** [comment]
Other candidate icons

![image](https://user-images.githubusercontent.com/23453691/199692654-855edc21-8e3a-4025-ad9c-1767353ca578.png)

![image](https://user-images.githubusercontent.com/23453691/199692922-962d77d4-036b-4474-ab34-c2a95eef01a2.png)

![image](https://user-images.githubusercontent.com/23453691/199693240-027a556b-8e53-4217-9c6b-99a0b1ec0e6b.png)

**Comment by valentinoli** [comment]
Demo:

https://user-images.githubusercontent.com/23453691/200066889-7deccfcf-7e3c-414d-a6aa-a160b5fd860c.mp4

The user is now only prompted for the codeword when entering an experience. The behavior was changed as part of modularization.

Moved to Specs done. A couple of questions to bizdev:

* Do you want data space links on the home page still to be removed altogether, as Alex mentions in the description?
* Is the icon OK? I took it from the bubble server repo's README

**Comment by alexbfree** [comment]
This is implemented and working and deployed, valentin is awaiting @hestiaAI/bizdev feedback.

**Comment by valentinoli** [comment]
Still waiting for feedback

**Comment by valentinoli** [comment]
Too long time passed so I will close now, assuming bizdev is happy.
