### ISSUE TITLE
Add Netflix instructions to Netflix Experience

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1108]
For a customer we need to add Netflix instructions, as this experience https://digipower.academy/experience/netflix differs from our others in terms of not having instructions.

The instructions are:

1. Go to https://www.netflix.com/account/getmyinfo and log in if needed.
2. Click Submit Request
3. Confirm the Request in your email
4. Await the files by email some days or weeks later.

**Comment by valentinoli** [comment]
In this case I think it's enough to set

```json
{
  dataPortal: 'https://www.netflix.com/account/getmyinfo'
}
```
