### ISSUE TITLE
Add parameter to allow missing files in archives

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#111]
In some cases, empty files are not included in the downloaded data (e.g. for Facebook). If a file is missing, the processing will fail for all the files. This should be handled differently, users should still be able to finish the experience.

This error appears when clicking "Process files"
```
Error: data/ad-engagements.js is not present in the archive twitter-incomplete.zip
    _callee$ unzip.js:31
    _callee2$ unzip.js:25
    extractFiles unzip.js:10
    _callee$ process-files.js:128
    _callee2$ process-files.js:125
    processFiles process-files.js:115
    _callee2$ UnitFiles.vue:296
    click BaseButton.vue:13
    click VBtn.ts:163
```

**Comment by valentinoli** [comment]
Ah, ok. This can easily be changed. However, the question arises whether you want the processing to be strict for certain data sources where files are required/expected to be present, for example Twitter experiences, and permissive for others like Facebook. If so, then we should add a new config parameter.

**Comment by valentinoli** [comment]
Perfect
