### ISSUE TITLE
Allow typed / pasted file paths when selecting secret key

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1114]
In https://github.com/hestiaAI/hestialabs-experiences/issues/1099 Paul's video shows an issue where he did not want to select his secret key because it would show his directory structure. We should allow a full path/filename to be typed/pasted, not just selected from directory selector.

**Comment by valentinoli** [comment]
> We should allow a full path/filename to be typed/pasted

I don't think this is possible. Browsers do not allow direct access to the file system for security reasons.

**Comment by alexbfree** [comment]
Closed as not possible
