### ISSUE TITLE
Set theme in nuxt, not in data-experience

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#1151]
The theme is updated in [TheDataExperience](https://github.com/hestiaAI/hestialabs-experiences/tree/968fd5e53e8f79ab52e97782a15c3359c99a8796/data-experience/src/components/TheDataExperience.vue)

The result is that a theme loaded from a config is only applied once you go to an experience. (The theme is also not applied if you load the url of the experience directly, but that's a bug).

We want the theme to be set when any page is loaded, so it should be the responsibility of whoever manages the whole site, not of one component. 

For the same reason, the functionality of loading a configuration and merging it with a default configuration that is currently also done in TheDataExperience should also be moved to the nuxt app.

**Comment by alexbfree** [comment]
Prioritized as Medium as this blocks us from customising the UI

**Comment by valentinoli** [comment]
> The result is that a theme loaded from a config is only applied once you go to an experience. (The theme is also not applied if you load the url of the experience directly, but that's a bug).

Fixed that 

> We want the theme to be set when any page is loaded, so it should be the responsibility of whoever manages the whole site, not of one component.

Yes, but we would like to enable 3rd party users of the data experience module to customize theme without hassle. That's why we do it for them in the data experience module based on the theme options they provide in the site config.

> For the same reason, the functionality of loading a configuration and merging it with a default configuration that is currently also done in TheDataExperience should also be moved to the nuxt app.

Same reason as above, we want to make it easier to use the data experience module, that's why we have default config.

**Comment by valentinoli** [comment]
I'll close this now

@andreaskundig feel free to comment/reopen if you think something needs to be addressed.
