### ISSUE TITLE
🐞 [BUG]: Change the link in the Weekly live data analysis with PO from eventbrite to Twitch

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Please register [here](https://www.eventbrite.ch/cc/weekly-live-data-analysis-with-paul-olivier-dehaye-1269769#) --> this is obsolete

### Expected Behavior

Please follow us [here](https://www.twitch.tv/digipoweracademy)

### Images

<img width="908" alt="image" src="https://user-images.githubusercontent.com/81250365/201676021-d8ed82c7-1741-4777-a8cb-2bc738f889f5.png">

### Steps to Reproduce

.

### Web Sites

digipower.academy

### Browser

.

**Comment by valentinoli** [comment]
The change has been done but not deployed. There is an error in ansible we're trying to resolve.

https://media.discordapp.net/attachments/1042425598573813763/1042428321025237033/image.png?width=1440&height=259
