### ISSUE TITLE
Charts should not need a vuex store, I think

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#1161]
The mixin for charts tries to access the name of the current tab, but we want to be able to use visualizations outside of experience tabs.

```
  data() {
    return {
      graphId: 'graph_' + this.$store.state.xp.currentTab,
      totalCount: 0,
      filterCount: 0
    }
  },

```
https://github.com/hestiaAI/hestialabs-experiences/blob/431db2037d831d646549b9e0b40acef30c232526/data-experience/src/components/chart/view/mixin.js#L21..L28

**Comment by valentinoli** [comment]
Yes, this can be avoided
