### ISSUE TITLE
🐞 [BUG]: Wrong link in the Google takeout experience

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

When you click on "cliquer ici" in the first tab of the Google takeout exp, the link sends you to the Uber download portal

![image](https://user-images.githubusercontent.com/81250365/202421152-1c18e9d5-7bd7-4076-b175-1893120659c9.png)

### Expected Behavior

it should send the user to takeout.google.com

### Steps to Reproduce

.

### Web Sites

digipower.academy

### Browser

.

**Comment by andreaskundig** [comment]
The code is fixed, close the bug when it is deployed.
