### ISSUE TITLE
🐞 [BUG]:  Generic Date viewer not working on CSVs

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

We get a No relevant data found on Linkedin experience for example.

### Expected Behavior

The Generic date viewer should include CSVs in its computation.

### Steps to Reproduce

Run Linkedin experience with sample data

### Web Sites

digipower.academy

### Browser

All

**Comment by valentinoli** [comment]
Issue was not that the viewer isn't supporting CSV files, it was the date format that was missing
