### ISSUE TITLE
RDF generation loops when YARRRML has rules for a file missing in the zip

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#124]
After the implementation of #111, it is now possible to have missing files in the zip archives. The processing of these files works correctly, and the content of the files is passed to the UnitRdf component as normal.

However, if we provide YARRRML rules about a file that is missing in the archive, the button "Generate RDF" will loop indefinitely.

We also get the following error message :  `DataCloneError: The object could not be cloned. rdf.worker.js:19`

**Comment by valentinoli** [comment]
Nice fix
