### ISSUE TITLE
Reuse graphs between queries and experiences

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#148]
This is a long term, non-urgent issue

We would like to reuse graphs between queries and experiences
- [ ] set the labels of a graph to match the names of the parameters in the query
- [ ] Find a way to match the type of a query result with generic d3 graphs
  - [ ] give the graph a way to advertise what types it accepts
  - [ ] find a way to discover the types of a query's results

**Comment by alexbfree** [comment]
close as old
