### ISSUE TITLE
Reusable components

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#150]
# Modules

We might want to deploy experiences outside of our application. There&rsquo;s a remote possibility that we take part in an external project based on jupyter. If our pipelines and visualizations were modules published on a cdn, we could use them in jupyter in a similar way to [this](https://www.jitsejan.com/using-vuejs-in-jupyter-notebook). It&rsquo;s likely that we want to deploy an experience as a part of another website, a collective or a partner.

I see several steps towards this (maybe we don't need all of them)

## 1.  modules with good developer experience

The first step is to set up a way to work with modules in a way that offers a similar developer experience as having them in one repo.
    
from a signal message:
    
> if we put a vue visualization in a module, which is a dependency of the manifest, which is a depency of the application (assuming we set up things this way), ideally we would want to run the app in the browser, edit the code of the visualization and see it change in the browser.
> 
> If that&rsquo;s too complicated, we would need another way to work on the vue visualization and see it in a browser. In the module of the visualization, we would want to do npm run server and see just the visualization in the browser showing some example data. Storybook.js would be a way to do it, but there are probably simpler ways too. (just guessing about storybook actually, I&rsquo;ve never used it)
    
 Hopefully we can do that in a monorepo with one of the tools Valentin identified: [lerna](https://github.com/lerna/lerna/issues/1722), or [rush](https://rushjs.io/pages/advanced/watch_mode/)

## 2.  identify what parts go in modules

One way to separate modules could be this, (modules with more dependencies first)
    
-   the application module, the nuxt app that ties everything together
-   the experiences, specific to a company or an inquiry (currently a manifest)
-   the visualizations
-   processors and preprocessors
-   a common core: anything that we need to make the different parts work together
    
Start by separating the simplest thing out, like the pre/processors and the visualizations
    
Currently we have different versions of the application, with different experiences. All the code is in the same repo and the displayed experiences are specified in a json config file. Would it make sense to specify the experiences as imports in javascript (+ dependencies in package.json )? Would it shorten the build time?

## 3.  (by the way: have tests in the modules)

Make sure to have a simple test for each one, use [snapshot testing](https://www.digitalocean.com/community/tutorials/vuejs-jest-snapshot-testing-in-vue) for ui components

## 4.  export to cdn (or javascript files we can host ourselves)

This would allow us to use our components in places where we don't have a build step, as in the jupyter integration above. 

If we want to use a free cdn like jsdeliver, we would need to make our code open source, but we could also just host the js files on one of our sites.

## 5.  export to web-components

This would simplify using the components even more (see [here](https://github.com/mdn/web-components-examples/blob/master/popup-info-box-web-component/index.html)). We are already using web-components in the websites. (We might want to rewrite the [sar form](https://github.com/hestiaAI/website.template/blob/main/src/components/sar-helper/sar-form.js) in vue, by the way)
    
Vuejs components [can be published](https://vuejsdevelopers.com/2018/05/21/vue-js-web-component/) as [web-components](https://vuejs.org/v2/guide/#Relation-to-Custom-Elements)

# Versioning for experience manifests

This was the original title of this issue, but it&rsquo;s just one use case for reusable modules. Once everything above works, we&rsquo;ll be able to specify the experience version in the export zip file. When we upload the zip file, the import page will be able to get the correct version of the experience from the cdn and display any data.

**Comment by valentinoli** [comment]
I have been working on setting up a monorepo for the experiences, using lerna for package maintenance and webpack for bundling them.

**Comment by andreaskundig** [comment]
Paul-Olivier just mentioned that we might participate in an INRIA project that works with jupyter and was hoping to reuse some of our work in jupyter. That sounds like making separate modules for visualizations. (vue can be used in jupyter, see [this](https://www.jitsejan.com/using-vuejs-in-jupyter-notebook))

**Comment by valentinoli** [comment]
I pushed the first commit to https://github.com/hestiaAI/hestialabs

For the TS configuration I took this repo as an inspiration https://github.com/NiGhTTraX/ts-monorepo

I have not yet set up the webpack config so loading other files than TS is not working yet. Here is a guide for setting up webpack with TS https://webpack.js.org/guides/typescript/

I don't yet know how we want to organize data samples, SPARQL, Vega, and YARRRML yet and I think it needs to be discussed... 
One idea is to put for example all Vega files in one folder so they can be reused, and the same for SPARQL...

**Comment by valentinoli** [comment]
We also need to discuss how we see this working in dev. We might need the two repos to communicate in dev. But maybe we don't since we might be able to use the playground for developing experiences. But that might be unneccessary moving code and files around. I am just thinking out loud. In the end we might need to set things up so that in development the frontend repo imports from the local copy of the monorepo. Not yet sure how but I'm sure it must be possible.

**Comment by valentinoli** [comment]
I would also like to add that it would be good to filter the experiences, to know which experiences we are sure to keep and which should be deprecated in favor of others. For example, are we going to keep `twitter-advertisers` and `twitter-advertisers-sha`?

**Comment by andreaskundig** [comment]
You're right, I suspect we can deprecate a lot of them

**Comment by ffsinger** [comment]
I think that the current stance is to have one card per company, so we would keep only `twitter` and `facebook`, and deprecate `twitter-advertisers`, `twitter-advertisers-sha`, `twitter-targeting-information` and `facebook-test`

**Comment by andreaskundig** [comment]
>  We might need the two repos to communicate in dev.

If we have a monorepo, we should try to have everything it there at first. There should be a way to work on an experience you're developing and see your code changes rendered immediately as we have now. 

https://lerna.js.org/#command-bootstrap
> lerna bootstrap
>
> Bootstrap the packages in the current Lerna repo. Installing all their dependencies and linking any cross-dependencies.
>
> This command is crucial, as it allows you to use your package names in require() as if the packages were already existing and available in your node_modules folder.

I hope we can make that work with nuxt

**Comment by valentinoli** [comment]
(copied from Signal) 

I managed to set up webpack and TS with one root config which means less redundancy. I also simplified the experimental setup, removed all sparql and yarrrrml temporarily. I found out how to load non-code files (like icons, yml, rq) with the TS/webpack setup. I am loading the icons as inline data URIs.

With this setup any resources can very conveniently be shared among the experiences and even published as packages.

Sharing is still *possible* with the current setup but loading everything with webpack's require.context is not ideal.

Next step is to figure out how to actually publish the packages.

https://github.com/hestiaAI/hestialabs

**Comment by valentinoli** [comment]
Some links about npm workspaces vs lerna

https://docs.npmjs.com/cli/v7/using-npm/workspaces
https://stackoverflow.com/questions/64909635/is-lerna-needed-anymore-with-npm-7-0-0s-workspaces
https://medium.com/@vladimirgorej/things-i-have-learned-while-maintaining-javascript-monorepo-with-lerna-fd4f6a5692f5

**Comment by andreaskundig** [comment]
we could start by publishing packages to github
https://docs.github.com/en/packages/quickstart

We need a personal access token to publish to the github package repository
https://dev.to/sijils/publishing-npm-package-to-github-package-repository-5ane


That could be done by any user, but it would be better if eventually we used a token from user hestiaAI.

**Comment by valentinoli** [comment]
I just discovered `rush`, an alternative to lerna: https://rushstack.io/

**Comment by andreaskundig** [comment]
Rush has a lot more documentation than lerna. Hopefully it's better documented rather than more complicated.

**Comment by valentinoli** [comment]
First 2 packages published in version 0.0.1 :tada:

https://github.com/orgs/hestiaAI/packages

I finally found out how to do it just by reading [the docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry) 📖 

Later when we actually want to use the packages we need to follow the below instructions:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package

**Comment by valentinoli** [comment]
Collection of links to articles and repos I read to understand things better:
https://github.com/NiGhTTraX/ts-monorepo/tree/npm
https://medium.com/@NiGhTTraX/how-to-set-up-a-typescript-monorepo-with-lerna-c6acda7d4559
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
https://dev.to/xaviercanchal/monorepo-using-lerna-conventional-commits-and-github-packages-4m8m
https://dev.to/sijils/publishing-npm-package-to-github-package-repository-5ane

**Comment by valentinoli** [comment]
We might want to later add [semantic-release](https://www.npmjs.com/package/semantic-release) to the monorepo

Here is a package for semantic release in lerna projects
https://github.com/atlassian/lerna-semantic-release

**Comment by valentinoli** [comment]
@andreaskundig now we've reached a milestone

**Comment by valentinoli** [comment]
In light of the progress we've made, I'm going to close this meta-issue in favor of more specific issues.
