### ISSUE TITLE
Improve the look of the default experience on mobile

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#151]
The graphs are a bit far down the page, maybe we shouldn't start with a big field for the uploads

**Comment by valentinoli** [comment]
Isn't it natural to start with the upload? But I agree it should be improved... mobile first design?
The content inside the cards is too squeezed.

**Comment by valentinoli** [comment]
Closed after consulting with @fquellec 
Mobile experience is not priority since the app is not intended to be used on mobile, for computational reasons and other
