### ISSUE TITLE
Distinguish between The Eyeballs and Dating Privacy experiences

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#154]
In https://experiences.hestialabs.org put on one side the Eyeballs experiences and on the other the DP experiences and add for each "Made for The Eyeballs/Dating Privacy" with the respective links (https://eyeballs.hestialabs.org / https://dating-privacy.hestialabs.org/en/):
![Capture d’écran 2021-10-18 à 15 46 59](https://user-images.githubusercontent.com/81250365/137744990-f7f40394-8971-4a77-91b5-dabd372efa9b.png)

**Comment by valentinoli** [comment]
this requires that we group experiences by the collaborator field in the manifest

**Comment by foucault-dumas** [comment]
As more and more experiences will appear and some of them will be mutual to several collectives, wouldn't it be better to make a legend system with colors?
Each color/collective could be clickable to filter, what do you think?
![image](https://user-images.githubusercontent.com/81250365/141966224-2bd11198-5750-4082-a264-84a1812f69e0.png)

**Comment by valentinoli** [comment]
> As more and more experiences will appear and some of them will be mutual to several collectives, wouldn't it be better to make a legend system with colors? Each color/collective could be clickable to filter, what do you think?

I think this is too complicated for now. We can implement this later if we think it simplifies the current arrangement.
