### ISSUE TITLE
Add a button to Luã's Ads Prices extension on https://experiences.hestialabs.org

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#155]
The user should be able to reach the Ads Prices experiment as easily as he/she reaches the other experiences. This button could link to the https://github.com/hestiaAI/my-worth-extension/blob/main/README.md content but hosted on a https://experiences.hestialabs.org/Ads-Prices page. 
![Capture d’écran 2021-10-18 à 16 23 22](https://user-images.githubusercontent.com/81250365/137751162-1b2c9eec-091e-484c-889f-f81fb0561ac7.png)

**Comment by valentinoli** [comment]
@foucault-dumas Instead of displaying the README in the app I would suggest just linking to it. So the user would click the card and be navigated to the README on GitHub

@streitlua any thoughts?

**Comment by foucault-dumas** [comment]
> @foucault-dumas Let me know if I understand this correctly:
> 
> You want a `/ads-prices` page in the app to display the content of the README for the My Worth extension. Would it not be better to let the page be `/my-worth` and the title "My Worth" instead of "Ads Prices" and the subtitle "How is your attention monetized?" for example instead of simply "Data Experience"
> 
> What do you think?

Sorry I wasn't clear: I think we should change the name "My Worh" for "Ads Prices" everywhere. That's why I proposed /ads-prices (I submit this proposal to the vote in The Eyeballs Signal group and come back here with the result)
For the subtitle, yours "How is your attention monetized?" is better than "Data experience" indeed
