### ISSUE TITLE
Complexify the query for SARs

### ISSUE THREAD

**Issue by pdehaye** [hestiaAI/hestialabs-experiences#174]
We want to complexify the query for SARs to enable for instance The Eyeballs page to target social networks and adtech companies. This means upgrading a bit the SPARQL query and using the right data from the wiki, where I have started defining the target types for each collective.

**Comment by andreaskundig** [comment]
Target types are defined for the eyeballs collective, for example

**Comment by andreaskundig** [comment]
Done

The documentation was updated in [website.docs/cms-quick-start](https://github.com/hestiaAI/website.docs/tree/main/cms-quick-start#how-to-configure-the-list-of-sar-recipients)

(This issue unrelated to this repo by the way, the right place for it would have been in [website.template.factory](https://github.com/hestiaAI/website.template.factory/issues))
