### ISSUE TITLE
Unify UnitCsvViewer and UnitQueryResults

### ISSUE THREAD

**Issue by streitlua** [hestiaAI/hestialabs-experiences#180]
Right now `UnitCsvViewer.vue` and `UnitQueryResults.vue` do almost the same thing although they serve different purposes.
1. `UnitCsvViewer.vue` takes a csv file as prop and displays its content in a table
2. `UnitQueryResults.vue` takes table data (headers + items) returned by `UnitQuery.vue` and displays it in a table

The idea would be to rename `UnitQueryResults.vue` to something like `UnitFilterableTable.vue`, and make `UnitCsvViewer.vue` use it.

Also, should `TheQueryResultsFilter` really exist as a standalone component?
Maybe we should integrate it inside `UnitFilterableTable.vue`, and have a boolean deciding whether we want the table to be filtered or not.

**Comment by ffsinger** [comment]
> Also, should TheQueryResultsFilter really exist as a standalone component?

@valentinoli

**Comment by valentinoli** [comment]
@streitlua 
The filter component was supposed to be for tables *and* visualizations right?

**Comment by streitlua** [comment]
My bad, I did not know that, we can keep it then :)

**Comment by ffsinger** [comment]
> The filter component was supposed to be for tables and visualizations right?

Ah yes I see now. Currently the graphs components are only using UnitQueryResults, but this gives the possibility of having the filters without showing the table.

But now that you mention it, I notice that the graphs are not affected by the filters (@fquellec)
