### ISSUE TITLE
A first integration test

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#191]
We need tests to catch regressions. If your new feature breaks an old feature, a test that fails should tell you about it. This first test will not catch many errors, but setting it up will make it easier to write more tests.

Set up a test that runs the application and opens an experience.
Configure github to run the test at every commit, or once a day. See github CI https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration

The application is built with nuxt, and was created with the [create-nuxt-app command line tool](https://github.com/nuxt/create-nuxt-app/blob/master/README.md). 

One way to go about adding tests would be to see if the command line tool can add a testing framework after the fact. If not, youc ould follow the conventions of that tool to install a testing framework by hand. On the other hand, maybe there's another good way of adding a test framework to a nuxt app.

There are several test frameworks to choose from. I worked with Jest in react, it seems it's also a popular option for vue. Maybe do a quick search to see if there's anything that overwhelmingly better.

**Comment by valentinoli** [comment]
Have you considered End-2-end testing? Like Cypress: https://www.cypress.io/
I have not any experience with such frameworks - is this something you're looking for?

**Comment by andreaskundig** [comment]
I've used selenium tests before and they're a real pain. It looks like Cypress is something like it, it also runs in the browser, and that it works better, so why not try it out. Apparently they have a github ci integration too, but does this mean github ci runs a browser? 

Apparently [people ](https://stackoverflow.com/questions/66217682/should-i-use-both-cypress-and-jest-together) are using it with jest and testing-library which are a bit lighter since they don't need a browser and can be used for unit tests. They would be sufficient for a simple integration test, so if we start with that we have something in place that also helps us write more fine grained tests.

The simpler frameworks like jest run without browser so there are less parts that can fail. Selenium was a pain in part because it depends on the browser and new browser versions meant that new drivers needed to be installed constantly, and tended to break tests. I don't know how cypress deals with this, probably better, but I think there is less risk using a simpler tool at first. The simpler tool is also likely to run faster. Once we have that, we could try cypress too, it does look pretty cool.

**Comment by andreaskundig** [comment]
We have the two first tests

The only thing missing now is a test that loads the whole application. This would be the first integration test.

**Comment by andreaskundig** [comment]
I would expect that there's something in between e2e running in a browser, and component tests for every single component. 

There should be a way to instantiate the top component App and let it instantiate all its children. This is trivial to do in react, why would vue not have this very important feature? It may well be that [create-nuxt-app](https://github.com/nuxt/create-nuxt-app/blob/master/README.md) creates one by default if you choose to have tests.

I would recommend to try this first, and if it turns out to be difficult after all, use e2e testing.

**Comment by valentinoli** [comment]
@andreaskundig we might be able to close this one now?

**Comment by alexbfree** [comment]
closing as we already have something
