### ISSUE TITLE
Option to show UnitFileExplorer

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#192]
Currently the file explorer is displayed on every experience. Instead it should only be shown when an option is set to true in the experience json.

For example in *manifests/experiences/twitter/twitter.json*
```
  showFileExplorer: true,
```

**Comment by ffsinger** [comment]
Duplicate of #188

**Comment by andreaskundig** [comment]
Already implemented https://github.com/hestiaAI/hestialabs-experiences/pull/189
