### ISSUE TITLE
bug: file tree for generic data viewer is inconsistent

### ISSUE THREAD

**Issue by streitlua** [hestiaAI/hestialabs-experiences#202]
We use unzip from unzipit.js to extract content from a zip file.
To build a file tree for the generic data viewer, we rely on the fact that unzipit.js creates an entry for each file inside the zip, including folders.
However, this is not always the case, so we might have to create the file tree structure from the name of the files only.

**Comment by valentinoli** [comment]
@streitlua 

Sorry, I couldn't handle myself. Might this work? Try running it in the browser console

```js
const files = ['a/b/c.json', 'a/b.json', 'a.json', 'a/b/d.json']
const fileParts = files.map(f => f.split('/'))

const result = []

fileParts.forEach(arr => {
  cur = result
  arr.forEach((value, idx) => {
      if (idx + 1 === arr.length) {
          // leaf node
          cur.push({ value, children: [] })
      } else {
          const node = cur.find(n => n.value === value)
          if (!node) {
              const n = { value, children: [] }
              cur.push(n)
              cur = n.children
          } else {
              cur = node.children
          }
      }
  })
})
```

Output:

```js
[
    {
        "value": "a",
        "children": [
            {
                "value": "b",
                "children": [
                    {
                        "value": "c.json",
                        "children": []
                    },
                    {
                        "value": "d.json",
                        "children": []
                    }
                ]
            },
            {
                "value": "b.json",
                "children": []
            }
        ]
    },
    {
        "value": "a.json",
        "children": []
    }
]
```

**Comment by streitlua** [comment]
@valentinoli thanks for this! I am refactoring the code so that the whole file extraction pipeline is easier to modify and maintain :)
This way, I'll separate: 1. the extraction of all files from zips and inner zips; 2. the creation of a file tree structure from the list of files; 3. the creation of items suitable for `v-treeview`.

**Comment by valentinoli** [comment]
Sounds good! Good luck
