### ISSUE TITLE
Add experiences "available on demand" on https://experiences.hestialabs.org

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#215]
Please add experiments under construction or to come (Apple, amazon, uber, spotify, google... visible on test.hestialabs.org) to the experiences.hestialabs.org page. It must be clear that they are not clickable: Text "available on demand" + greyed out ?

**Comment by streitlua** [comment]
I'm working on it!
Would it be ok to have the text "Under construction..." instead? Would we really be able to answer any demands?

**Comment by pdehaye** [comment]
Why not "Contact Us"?

**Comment by foucault-dumas** [comment]
Yes, why not, but it means:

### Public experiences
FB / TW / AdRadar / Tinder (clickable)

### Other experiences ([contact us](mailto:contact@hestialabs.org))
Google / Apple / Amazon / Spotify / Uber / Netflix... (not clickable)

**Comment by streitlua** [comment]
Did you have something like this in mind? (we won't show these experiences exactly, this is just for testing purposes)
On the main page:
![image](https://user-images.githubusercontent.com/16099301/141959429-cdf8cdd5-21cb-4910-baa7-63706c5539b9.png)
![image](https://user-images.githubusercontent.com/16099301/141959464-21601c34-cdcd-4662-8898-da533cfc32e5.png)

In the side bar:
![image](https://user-images.githubusercontent.com/16099301/141959533-385f0a86-bd98-4064-bdc7-e379b07ca043.png)
![image](https://user-images.githubusercontent.com/16099301/141959585-795e5b3a-e776-408b-8c41-f2125c529740.png)

**Comment by foucault-dumas** [comment]
Yes, but, really, I would prefer "Other experiences" and to not display "not ready"
While you're here, would you mind changing "the newsletter of HestiaLabs" --> "HestiaLabs' newsletter" ?

**Comment by streitlua** [comment]
I'm still not sure I understand the goal of showing disabled experiences.

After discussing this with the team this morning, we found that "public experiences" vs "other experiences" can be confusing for users, will any experience actually be private?
Wouldn't "discover our experiences" vs "future experiences" be a better distinction?

What text would you like to show in the disabled experiences?

I will change the text for the newsletter.

**Comment by foucault-dumas** [comment]
Collectives need a business model, that is our commitment to Migros. For The Eyeballs (and maybe others) it will be paid training with these tools. The flyers I send to the prospects of these trainings offer a link to this page. We want these prospects to feel like we can do whatever they want, which is true, it's just a matter of time/choice of where we put our efforts.

That's why I'd like us to display not-yet-available experiences as "available on demand" (which I agree is a bit of a distortion of reality but not completely) rather than "not ready" or "future" which are much less engaging.

That's why I think the best is "Public experiences" and "Available on demand (contact us)" as titles for the 2 zones and « Data experience » instead of « not ready » for the subtitle of each disabled experience.

Is that fine for you?

**Comment by foucault-dumas** [comment]
Good point.
Maybe we can add a card with the same link as the "contact us" in the title, a question mark on it and the texts:
### More to come
#### Contact us for specific needs

Can we?

**Comment by streitlua** [comment]
So right now we have this:
![image](https://user-images.githubusercontent.com/16099301/141992318-d8b3491f-beb2-41f0-afaf-d7226a9176e7.png)
![image](https://user-images.githubusercontent.com/16099301/141992360-f5156c16-573f-433b-a158-f5b6fd54b473.png)
![image](https://user-images.githubusercontent.com/16099301/141992416-23f0100d-5426-4c24-ab06-2be9753b38c9.png)
![image](https://user-images.githubusercontent.com/16099301/141992506-02471278-879c-4349-bfbc-a44b26233dda.png)

Seems good?

**Comment by foucault-dumas** [comment]
Thanks! 😊
