### ISSUE TITLE
All experiences are accessible through URL

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#218]
Example: https://experiences.hestialabs.org/twitter-advertisers should not exist on this deployement. Is there a way to take them out of the build ?

We can also access "unavailable" experiences such as https://experiences.hestialabs.org/apple.

**Comment by valentinoli** [comment]
Wasn't that the purpose of the configs?
config/config.json for experiences.hestialabs.org

**Comment by valentinoli** [comment]
> https://experiences.hestialabs.org/twitter-advertisers should not exist on this deployement

but `twitter-advertisers` is defined in the config, right?

**Comment by valentinoli** [comment]
Sorry, I see now that it is workshop.json for experiences.hestialabs.org

**Comment by valentinoli** [comment]
So something is wrong with the navigation guard

**Comment by ffsinger** [comment]
I spent some time looking at this and I don't know how to fix it.

- It seems that nuxt automatically generates routes from the possible values that `m()` can take in `pages/_key.vue`.
- `m()` can take all values that are defined in the `manifestMap` of `store/index.js`. 
- `manifestMap` contains the full set of experiences. Only the getter `manifests` contains the filtered list of experiences
- If I try to use the getter `manifests` instead, it breaks all pages.

**Comment by ffsinger** [comment]
Ideally, the experiences that we don't want wouldn't even be read by webpack in `manifests/index.js`, but it's hard to do since `require.context` can only take literals as argument

**Comment by valentinoli** [comment]
> Ideally, the experiences that we don't want wouldn't even be read by webpack in `manifests/index.js`, but it's hard to do since `require.context` can only take literals as argument

Yes, that will be solved when we use packages

**Comment by valentinoli** [comment]
> * It seems that nuxt automatically generates routes from the possible values that `m()` can take in `pages/_key.vue`.

I don't think this is happening. Where would we be telling Nuxt that `m` is a list of routes?

**Comment by ffsinger** [comment]
> What happens is that a single route entry is created for _key.vue with a parameter "key" and it is up to us to validate the route, which we didn't do properly.

I see, thanks for the fix !
