### ISSUE TITLE
Sunburst is not updated

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#219]
On the second sunburst, where we have to input the advertiser, the sunburst is not updated when we try with another advertiser.

The new values are correctly passed to `Sunburst.vue`, but then nothing happens. Similarly to #178, I tried adding this in `Sunburst.vue`:

```
watch: {
  values(oldValues) {
    this.drawViz()
  }
},
```

But it duplicates the sunburst instead of replacing it. I don't know what would be the cleanest way to solve this, but from my basic understanding of D3 we wouldn't really need to recall the entire function, we would just need to do the data processing step (i.e. recreate the `root` object in this case), and then the viz would be updated automatically by D3.

**Comment by valentinoli** [comment]
Small comment, the `oldValues` should really be called `newValues` since the first parameter is the new value and the second one is the old value

**Comment by valentinoli** [comment]
Btw, I'm working on refactoring components in PR #226 and at the same time adding a mixin for these chart components where this watcher can be added (assuming it is used in all of the components)

**Comment by ffsinger** [comment]
Oops, sorry about the confusion on the arguments, and thanks for explaining the best practice

**Comment by fquellec** [comment]
fixed in #234
