### ISSUE TITLE
SQL DB and RDF Store are exported as a global instance

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#233]
As discussed in the dev meeting, we may want to have multiple instances of these objects in the future. So they shouldn't be exported directly as a new instance accessible from anywhere in the code.

**Comment by valentinoli** [comment]
Maybe a factory could be exported and the instances for the user stored in Vuex?

**Comment by andreaskundig** [comment]
I was also thinking that we're not using vuex enough

**Comment by valentinoli** [comment]
@andreaskundig I assume this one can be closed
