### ISSUE TITLE
Facebook experience broken

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#241]
When I try to upload my zip file (3.3 GB), I get this error in the upload module:
![image](https://user-images.githubusercontent.com/17878016/143207450-d074dcf3-756b-450b-8c3a-5a20517a4507.png)

When I use the Charles archive (200Mb), I pass the upload but I get this error when running the first cell:
![image](https://user-images.githubusercontent.com/17878016/143218721-f545697c-8241-4c33-8f03-25b4705b6cd2.png)

Using Annaelle's archive (20Mb) everything works.

The archives are available on the kDrive under Projects/TheEyeballs

**Comment by streitlua** [comment]
It seems that this is related to the extraction of the files using the library `unzipit.js`.
I found the [code where the error is thrown](https://github.com/greggman/unzipit/blob/master/src/unzipit.js#L201) and I think that the problem is either related to a malformed zip archive, or to the large size of the given archive.

**Comment by streitlua** [comment]
I tested the Facebook experience with Charle's and Anaelle's archives and everything worked correctly.
Could you check if your zip archive is formatted correctly? Maybe try extracting everything from it and creating a new one.

**Comment by streitlua** [comment]
Actually, there is indeed a problem on the first viz with Charle's archive, apparently the data validator fails. I'm investigating.

**Comment by streitlua** [comment]
There shouldn't be any more issues with the facebook experience (other than the fact that it's currently running on the sparql pipeline which is very slow)
