### ISSUE TITLE
Generic location viewer

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#266]
Like the generic date viewer, the generic location viewer should extract location data from any kind of files.

The locations could be displayed in kepler inside a UnitIframe. The update function needs to be modified in order to accept data in another form than a big csv string.

**Comment by pdehaye** [comment]
It tends to be that geolocation data is provided by CSV when there are lots. 
There is a lot of variability in how latitude longitude are defined. For instance as decimal value separated by a comma or a dot. With headers with different components such as 'xxxx_lat', 'xxxx_lng', or with 'latitude' fully spelled out.
