### ISSUE TITLE
Content Sharing with Web Share API

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#286]
Supersedes https://github.com/hestiaAI/data-pipelines/issues/27 (please read that issue first)

[Integrate with the OS sharing UI with the Web Share API](https://web.dev/web-share/)
[Receiving shared data with the Web Share Target API](https://web.dev/web-share-target/)

[Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API)
[`Navigator.share()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by valentinoli** [comment]
Created a PR in the polyfill to support Facebook hashtag sharing 
https://github.com/on2-dev/share-api-polyfill/pull/79

For devices that actually support Web Share, I guess we need to simply append the hashtags to the shared text.

**Comment by valentinoli** [comment]
Created a PR in the polyfill to support Twitter `via` parameter (which we used to provide to the deprecated `TwitterShareButton` component through the `twitter-user` prop)

https://github.com/on2-dev/share-api-polyfill/pull/80

**Comment by valentinoli** [comment]
`dom-to-image-more` not working for an iframe (tried to export the Kepler iframe to a PNG)
https://github.com/1904labs/dom-to-image-more/issues/57

**Comment by valentinoli** [comment]
> `dom-to-image-more` is not working for an iframe (tried to export the Kepler iframe to a PNG) and got an error
> [1904labs/dom-to-image-more#57](https://github.com/1904labs/dom-to-image-more/issues/57)

This is only an issue for us if we want the user to be able to share the Kepler map.

I'll close this issue for now and we can create new issues as problems arise or requirements change

**Comment by andreaskundig** [comment]
> `dom-to-image-more` is not working for an iframe (tried to export the Kepler iframe to a PNG) and got an error [1904labs/dom-to-image-more#57](https://github.com/1904labs/dom-to-image-more/issues/57)

Did you try adding the library to stat/kepler/index.html  as a script ?

``` html
<script src="path/to/dom-to-image-more.min.js" />
```

**Comment by andreaskundig** [comment]
There are now potentially several share buttons on a page:
- on the top right, for sharing a link to the page
- appears below every chart, after pressing export
- appears below every table, after pressing export

Since the webshare api is not implemented everywhere, the functionality differs according to browser and os. 


| OS  | Browser | experience |chart|table|
| ------------- |||||
| windows   | firefox     | WORKS: facebook, twitter, linkedin| no share button| no share button|
|    |      |  FAILS: whatsapp, skype| | |
|    |      |  UNTESTED: pinterest, telegram|| |
| windows   | chrome     | WORKS: twitter app| WORKS: twitter app| only shares link to page: twitter app|
|    |      |  MISSING: twitter web, facebook web|MISSING: (same)|MISSING: (same)|
| android   | firefox     | works | no share button| no share button|
| android   | os     | works | works|works|

**Comment by andreaskundig** [comment]
@foucault-dumas @pdehaye this is the state of social sharing on experiences. It hasn't been tested on the iphone or on Safari yet.

**Comment by foucault-dumas** [comment]
Thanks a lot @valentinoli and @andreaskundig for this new feature!

Why shall one export before sharing??

I couldn't test it on macOS:

## maOS

### Chrome
No sharing possibility except experience

### Safari
No sharing possibility on the "Top Advertisers" module
On the other moduls and on experience the share button opens the [MacOs share extension menu](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/)
![image](https://user-images.githubusercontent.com/81250365/148926403-261af290-84d6-425a-a724-6b95b65fe13f.png)

### Vivaldi
No sharing possibility except experience

**Comment by valentinoli** [comment]
> Why shall one export before sharing??

@foucault-dumas 
It is because for security reasons the browser blocks programmatic sharing. Invoking the `share()` function can only be done as a direct result of a user action. For this reason, having a single button that does both the exporting and sharing does not work.

**Comment by valentinoli** [comment]
I encourage you to read [this article](https://web.dev/web-share/). It is updated regularly as browser support improves.

> With the Web Share API, web apps are able to use the same system-provided share capabilities as platform-specific apps. The Web Share API makes it possible for web apps to share links, text, and files to other apps installed on the device in the same way as platform-specific apps.

**Comment by valentinoli** [comment]
[Web Share API browser support](https://caniuse.com/web-share)
[File sharing browser support](https://caniuse.com/mdn-api_navigator_share_data_files_parameter)

**Comment by valentinoli** [comment]
Interesting potential feature of the API that we might want to take advantage of in the future:

[Receiving shared data with the Web Share Target API](https://web.dev/web-share-target/)

**Comment by foucault-dumas** [comment]
> > Why shall one export before sharing??
> 
> @foucault-dumas It is because for security reasons the browser blocks programmatic sharing. Invoking the `share()` function can only be done as a direct result of a user action. For this reason, having a single button that does both the exporting and sharing does not work.

Can't the export be systematic (automated)?
