### ISSUE TITLE
Use workers when needed to avoid freezing the UI

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#288]
This issue is related to https://github.com/hestiaAI/digipower-data-experiences/issues/67. 

When uploading large files, some experiences crash or freeze the screen for a long time. Using workers for complex tasks  has several advantages that I can think of:
- The rendering of the application does not depends on some subtasks, the user can still interact with sub-experiences if one of them takes time to process.
- We could manage, allow the user to stop a task that takes too much time. 
- If one task fails the rest of the experience can still work-

Here are some of the places where workers could be useful (feel free to add more or correct me): 
- Generic and non-generic pipelines, we could use workers for the preprocessing of the data for each sub-experiences.
- Inside the File explorer, calculating the number of data points in the file explorer is not essential and takes a lot of time, we could first display the file explorer without this number and update it when it is ready.
- ...

The Web worker library [worker-loader](https://github.com/webpack-contrib/worker-loader) is already installed in the project.

Note by @valentinoli for functions that are not serializable: 
> However, that is not possible since they are not serializable by the structured clone algorithm.
> Therefore, we define all functions globally and import them here.
> https://stackoverflow.com/a/7705809/8238129
> https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
> See here for possible solutions if we want to later define the functions locally per definition:
> https://dev.to/localazy/how-to-pass-function-to-web-workers-4ee1
> https://github.com/vkiryukhin/jsonfn

**Comment by andreaskundig** [comment]
slq.js can be used as a [worker](https://sql.js.org/#/?id=use-as-web-worker). 

Currently importing data into the database takes up the most time when processing a twitter file. We could batch the inserts and run them in parrallel in different workers.

**Comment by ffsinger** [comment]
The web worker that can be imported from sql.js does not seem to work with webpack, so what we could do instead is to write our own web worker for the database operations.
