### ISSUE TITLE
Bug with Google Experience

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#332]
Hi, I downloaded my Google data per the standard instructions we are giving to participants (I will attach contents list below)

However the file was not loadable in our Google experience. It caused the browser to hang for a minute or two 

![one](https://user-images.githubusercontent.com/1473244/145997490-42a34c96-b986-4dbe-b0b4-d0922b1b384d.png)

and even when I regained control, no data was displayed 

![two](https://user-images.githubusercontent.com/1473244/145997561-f73a0296-1e8f-4348-b212-015f23cbe125.png)

and eventually the page auto-reloaded, I guess because it couldn't complete rendering)

![three](https://user-images.githubusercontent.com/1473244/145997575-18673038-0d3f-407f-9d0e-5a757518d566.png)

**Comment by ffsinger** [comment]
I think that the problem is not directly related to the Google Experience, but probably more to the fact the zip contains 5534 files and 1.65 GB

**Comment by alexbfree** [comment]
That count is incorrect tho, the file was 175Mb

**Comment by ffsinger** [comment]
There may be some compression going on then. 175MB compressed and 1.65GB when unzipped

**Comment by alexbfree** [comment]
BTW here is an extract from the instructions we are using:

of these don't appear for you, it just means you don't use them so can ignore. You can also omit any that you don't wish to see the data for.
> 
>     Arts & Culture
>     Chrome
>     Crisis User Reports
>     Data Shared for Research
>     Fit
>     Google Account
>     Google Cloud Search
>     Google Help Communities
>     Google Pay
>     Google Play Books (options on this need changing - see step 6 below)
>     Google Play Games Services
>     Google Play Movies & TV (options on this need changing - see step 6 below)
>     Google Play Store
>     Google Shopping
>     Google Store
>     Google Translator Toolkit
>     Google Workplace Marketplace
>     Google Hangouts
>     Home App
>     Keep
>     Location History (options on this need changing - see step 6 below)
>     Maps
>     Maps (Your Places)
>     My Activity (options on this need changing - see step 6 below)
>     My Maps
>     News
>     Pinpoint
>     Profile
>     Purchases & Reservations
>     Question Hub
>     Reminders
>     Saved
>     Search Contributions
>     Tasks
>     YouTube (TWO options on this need changing - see step 6 & 7 below)
> 
> 5. You can add others that may appear for you that are not listed here if they are of interest, but take > care NOT to select (as they may be large or cause delays):
> 
>     Access Log Activity (not to be confused with 'My Activity', which you *must* select)
>     Blogger
>     Classic Sites
>     Drive
>     Google Business Profile
>     Google Groups
>     Mail
>     Photos
>     Street View
>     Voice
>     The 'videos' checkbox within YouTube.
> 
> 6. For the following entries, you need to change the download format to one that will be better structured for use in viewing tools like ours. This is done by clicking the leftmost button in the row (usually says "HTML format" or "Multiple Formats") and using dropdowns to change any options to JSON format:
> 
>     Google Play Books -> Change 'Play Books Metadata' HTML to JSON
>     Google Play Games Services -> Change all 7 HTML dropdowns to JSON
>     Google Movies and TV -> Change 'Movies & TV Data' from CSV to JSON
>     Location History -> Change format from KML to JSON
>     My Activity -> Change 'Activity Records' format from HTML to JSON <-- IMPORTANT
>     Profile -> Change 'Inactive Account Manager settings' from HTML to JSON
>     YouTube -> Change 'Viewing history' from HTML to JSON
> 
> 7. For YouTube, also click the right hand button in the row "All YouTube Data included" and UNCHECK the 'videos' checkbox. This is very important if you have ever uploaded a video to YouTube.

**Comment by alexbfree** [comment]
If you can spot any me should move from step 4 to step 5 let us know

**Comment by alexbfree** [comment]
Can someone try following these steps and see if it works for you & your data?

**Comment by alexbfree** [comment]
@streitlua has deployed a version to test.digipower which doesn't count datapoints. this alleviates a lot of the issues (but not for locations view)

**Comment by alexbfree** [comment]
assigning to self for testing

**Comment by valentinoli** [comment]
@alexbfree is this done? Can it be closed?
