### ISSUE TITLE
[was #98] Show JSON as nested tables with option to switch to twistie view

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#346]
Another thing we thought of in Deep Dive:

Add an option to toggle between a Table view and a Twistie/List view at each node in JSON view

Default to Table view if no data strings would show up in the collapsed twistie label.

Recommend using flexbox/flexgrid so that you can support deep levels of nesting

**Comment by alexbfree** [comment]
The links to 113 discussion now refer to #391

**Comment by alexbfree** [comment]
OK, so based on recent discussions I want to clarify that:
- this is for the 'best guess' viewing of generic and possibly unknown data NOT based on specific data knowledge acquired through #391 #400 etc.
- I think it's possible to do a very generic and crude solution to this where the Table view would *replace* the tree view, not where we would have different tree-or-table views at different depths (as that brings a lot of complexity.

For my next step I will try and flesh out this requirement a bit more to make this ticket workable on.

For now, this can stay on hold while we focus on #400.

**Comment by andreaskundig** [comment]
Like Lua said yesterday, the treeview component we're using has limited configuration options and does not allow replacing a node with a table.

A possible replacement we discussed would be to allow the user to click on a table icon next to a node, and display it as a table that appears below the treeview.

**Comment by alexbfree** [comment]
I agree with this proposal but I have opened a new ticket #408 for this.

This ticket #346 remains to focus on the possible design of a "table view from top level down" approach as a toggleable alternative to tree view. I will come up with a design for this.
