### ISSUE TITLE
[was #120] Is 'custom audiences' view missing from Facebook experience?

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#349]
@pdehaye said there was a missing 'custom audiences' view on the Facebook experience on Digipower that we have got available on other instances/Facebook experience versions.  Please can this be added.

**Comment by fquellec** [comment]
Done in https://github.com/hestiaAI/hestialabs-experiences/pull/344
![image](https://user-images.githubusercontent.com/17878016/148187437-3d91165e-96f0-4b6b-badd-70f053fed624.png)
