### ISSUE TITLE
Improved solution for Selecting Files To Export

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#352]
Thanks to @ffsinger for the brilliant work on hestiaAI/digipower-data-experiences#88 (integrated with @streitlua's work on hestiaAI/digipower-data-experiences#74), this is a good solution.

However, having seen the two features together I think the UX can be improved.

As someone previously observed, the checkboxes are a little confusing to the normal file browsing process, in fact I think they should be removed from the default file explorer left nav, for two reasons, firstly less confusion during browse, and secondly, moving file selection inside the consent form will allow better feedback to user about which files are currently selected. Also file selection is conceptually, part of the mental workflow of sharing/thinking about consent, not part of the workflow of file browsing.

So, can we remove checkboxes entirely from the file explorer, and produce a file selection popup/modal within the consent form, when you tick the "Selected Files" purpose, that shows the hierarchy tree and allows you to check/uncheck/select all/unselect all and then press "Confirm Selection"?

Once the popup has closed the checkbox text on the purpose should update to show details of what was selected:
`[ ] Selected Files (8 files selected: [view list])`
Where [view list] would be a link that pops up a list of the currently selected files.

**Comment by ffsinger** [comment]
This has already been implemented+tested and has a follow-up issue #350. Closing this one
