### ISSUE TITLE
Change the approach for loading files/restricting files/finding needed files

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#353]
As a general approach for all experiences (I speak for digipower, Charles/Paul can confirm whether this applies globally, I expect it does) we should not be restricting what files people upload. At the moment some experiences (such as Netflix) are locked to Zip and some others (such as Spotify) are locked to 1 file.

The general idea is people drop whatever they have (maybe the original zip, maybe some subset of files from what they unzipped, maybe just a single file) and we try and make sense of it.

If we can't find a file that we need (as an initial assumption we can go by the filename or path, but we may need to be cleverer than that in future) then we should just give a meaningful error message.. we couldn't display this view because we didn't find this file that we need.

In fact, we may want to consider presenting a list of "expected files/files we will use" for each experience (perhaps hidden under an info (i) popup or something) at the top of every experience.

**Comment by alexbfree** [comment]
Discussed in standup today. 
Agreed that @alexbfree will make a ticket for just the last part. The rest is deferred pending other developments on refactoring/accessors [Sorry, I can't remember if it was @fquellec or @andreaskundig who was due to make a ticket for the outstanding work this depends upon]. 

Once those two new tickets exist I will put this one on hold.

**Comment by alexbfree** [comment]
Incidentally we have now had 2 participants share their twitter data in this format of `twitter-YYYY-{longID}/data/` subdirs so I guess the format they deliver in has changed? (or maybe different for SAR vs download portal). Anyway, this shouldn't matter once this is fixed.

**Comment by ffsinger** [comment]
#498 relaxed the restrictions for **ZIPs**. Now the files needed for Twitter, Facebook and Uber can be at any level in the archive.

One point that was not addressed is that we are still expecting a zip, so the user cannot just upload one unzipped file for these experiences. I suggest that you open a new issue if this is still needed, so that this ticket can follow the standard process (merged -> deployed to test -> deployed to digipower)

**Comment by alexbfree** [comment]
OK I have created #501.

@ffsinger @andreaskundig @fquellec please can you all confirm it is OK to close this ticket once #498 is in production

(I previously got the impression there may be some other outstanding refactoring work, hinted at previously, that requires this ticket to stay open)

**Comment by alexbfree** [comment]
On digipower currently - Uber is not finding the `trips_data.csv` if it is not in a folder called `Rider` in an `Uber Data` top level folder. Not sure if we expect this should have been fixed yet.

**Comment by alexbfree** [comment]
I don't have access to example Driver data ... so let's change it to `**/Rider/trips_data.csv` ? they may no longer have the "Uber Data" folder so we shouldn't rely on that for any of the imported files.

**Comment by ffsinger** [comment]
Ok this is fixed in commit 1bb14626e28262109b454b3dbf518f3c9d96b321
