### ISSUE TITLE
Generic Geolocation Experience

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#357]
This is the #digipower specific version of hestiaAI/hestialabs-experiences#266

We need something we can add to specific 'generic containers'.
That will give some view over locations found in the data, similar model to generic event viewer.

at least, a map with points (perhaps grouped into circles with number when lots in same area?) and some textual summary at top of number of datapoints / distinct lat-longs, cities, regions, countries found
Allow zoom in/out and pan
Respect date range (should ideally share same date selector as generic event viewer so as not to repeat)

Perhaps also: list of cities/regions/countries found. (I recognise that it is a huge endeavour to recognise any possible location, the detection of these may need to depend upon identifying fieldnames such as 'city' 'location' etc?)

**Comment by ffsinger** [comment]
I checked, it's available for all these experiences. Closing
