### ISSUE TITLE
Change user cursor to Hourglass (and back afterwards) during any activity that might take time

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#363]
(excuse the brevity, adding tickets in a rush. Contact Alex or Paul for more details)

This is an issue when processing files and especially when clicking on a file or list/item expander twistie. Need a clear indication the app is actually doing something. App appears non responsive otherwise.

**Comment by ffsinger** [comment]
> Leaving this ticket open until 'All' is changed to 100.

'All' has been removed, users now have the following options: [5, 10, 15, 500, 1000]. Closing
