### ISSUE TITLE
Add summary of the zipfile contents/selected files at top of page (which could be top of generic event viewer

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#364]
(excuse the brevity, adding tickets in a rush. Contact Alex or Paul for more details)

Add summary of the zipfile contents/selected files at top of page (which could be within top of generic file viewer if hestiaAI/digipower-data-experiences#70 is done)

Should include:

- Number of files 
- Types of files
- Total size of data (mb)
- Number of datapoints (some measure of how complex/voluminous the files are)

There are this many files, this many megabytes at the top. Also around Explore your files. 

Can take inspiration from the summary in dated event viewer

**Comment by streitlua** [comment]
After #482, filenames are now clickable! 
I'm  unassigning myself from this ticket as I don't think I'm the best person for part 2 (and I've already tried doing it before without success).
