### ISSUE TITLE
Make the Process and Run buttons hidden and automatic

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#365]
(excuse the brevity, adding tickets in a rush. Contact Alex or Paul for more details)

Low priority, but we think these buttons add extra clicks and are not needed. All data viewers should populate once data is loaded.

**Comment by ffsinger** [comment]
Now that the experiences are separated in tabs (#424), we have multiple options:

- Run all the experiences automatically when the data is loaded. This can cause a long initial delay, and maybe the user is only interested in one specific sub-experience
- Run an experience automatically when the user switches to the tab. This reduces the problem above. However, what should happen if the user clicks on another tab before the current one has finished loading ? options: 
  - Kill the computation
  - Queue the computations
  - Do not let the user change tabs

**Comment by alexbfree** [comment]
Yes, I like the second option, run the experience when you switch to the tab.

I would reject queuing the computations, I don't think there are benefits for doing that.
This leaves the other two options of killing the computation or blocking tab change.

I don't have strong views on this, I guess killing the computation would result in a more responsive UI so would be slightly preferably if it is easy to do without side effects. If that is difficult or carries other impacts then blocking the tab change would be OK.

**Comment by valentinoli** [comment]
I think killing computation would be much harder to implement - unless the computation is done in a worker, then there is no way to interrupt the thread. But if the computation is done in a worker, I think it can be done simply by [`worker.terminate()`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate)

**Comment by valentinoli** [comment]
@ffsinger 
Did we consider using web workers for sql.js?

**Comment by valentinoli** [comment]
The best temporary solution in my view is to just disable the tabs and show a progress indicator. I implemented an overlay with a progress indicator that should only appear if a subexperience takes long.

**Comment by ffsinger** [comment]
> Did we consider using web workers for sql.js?

Yes it's planned to use web workers for the sql queries at some point

**Comment by andreaskundig** [comment]
I reverted the merge of #455 because it broke the implementation of #400 that allows the user to edit pipeline options. After changing the options, the user needs to be able to run the pipeline again, but #455 removed the run button.

**Comment by valentinoli** [comment]
@andreaskundig you mean #445 ?

**Comment by andreaskundig** [comment]
Yes, I corrected in the comment

**Comment by valentinoli** [comment]
@andreaskundig so what is the plan? We still want this feature, right?

**Comment by andreaskundig** [comment]
@valentinoli yes we still want the feature.

By the way UnitPipelineCustom now has an autoRun prop. Maybe this could be useful pattern to reuse for other pipelines.

**Comment by valentinoli** [comment]
@andreaskundig I think if we want all pipelines to automatically run, we don't need that prop anymore. Right?

**Comment by andreaskundig** [comment]
We might want to rerun them after having changed the input or the pipeline somehow. When a custom pipeline has options for example, you can edit them and rerun it. 

What we want now is that they are run automatically the first time.

If there's no way of changing what happens when you run it, then we could hide the button.

**Comment by valentinoli** [comment]
@fquellec @andreaskundig I suppose this can be closed?
