### ISSUE TITLE
Link out to system viewer for unrecognised file type within the zipfile /file list

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#369]
In Generic File Viewer, use file:/// link or some other technique to trigger system viewer.

Examples:

- .XLSX
- .7Z

**Comment by ffsinger** [comment]
I don't think we can do this without downloading the file

**Comment by valentinoli** [comment]
I think for security reasons the user must select the file and not the application - so I don't think we can do this

**Comment by alexbfree** [comment]
OK I will close this, we assume this is not possible for now.
