### ISSUE TITLE
[was #126] TableViewer

### ISSUE THREAD

**Issue by pdehaye** [hestiaAI/hestialabs-experiences#385]
I am sure somewhere in the code there is a table viewer. 

Can we have code that takes a JSON object and view specifications such as 
```
           "properties": {
                "advertiser_name": {
                    "type": "string"
                },
                "has_data_file_custom_audience": {
                    "type": "boolean"
                },
                "has_remarketing_custom_audience": {
                    "type": "boolean"
                },
                "has_in_person_store_visit": {
                    "type": "boolean"
                }
            },
            "required": [
                "advertiser_name",
                "has_data_file_custom_audience",
                "has_in_person_store_visit",
                "has_remarketing_custom_audience"
            ],
```
(i.e. parts of JSON Schema) to produce a table?

**Comment by alexbfree** [comment]
@fquellec I think this is done now (THANKS!) , what testing or next steps do you see as outstanding before the ticket can be closed?

**Comment by fquellec** [comment]
Hey ! I think we can close this ticket, everything described in it has been done, for the next steps we can continue the discussion here: https://github.com/hestiaAI/hestialabs-experiences/issues/400

**Comment by alexbfree** [comment]
:-)
