### ISSUE TITLE
Text Filter Feature in Event Viewer

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#386]
this is lower priority than getting all the base experiences ready

Once hestiaAI/digipower-data-experiences#30 is implemented, let's add a feature to filter the dataset (this should affect table AND graph AND summary) to only include rows where the entered filter text occurs within Description (where Description is a concatenation as described in hestiaAI/digipower-data-experiences#30)

The current filter should always be clearly displayed up top. (and removable).

Example, i could type TikTok and only rows which mention TikTok would be included in the table, or graph calculations, or summary calculations. 

ideally, this works in autocomplete type of way, but if it's not possible to do that performantly, then clicking a button after typing is fine.

**Comment by valentinoli** [comment]
@fquellec we need to re-create this one

**Comment by valentinoli** [comment]
#744
