### ISSUE TITLE
Tracker Control Table Filtering

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#388]
User Story: **As a participant, I can filter the trackercontrol data table by Category, Tracker, Date Range, App Name, or some combination of those filters**

Pre-requisite:

- hestiaAI/digipower-data-experiences#18 

Co-dependency:

If any of hestiaAI/digipower-data-experiences#21, hestiaAI/digipower-data-experiences#22, hestiaAI/digipower-data-experiences#23 are already coded when this is implemented, need to make sure that the filtering affects those graphs too. (could be delegated by reopening those closed graph tickets with a comment).

Details:

- Ability to filter the table by typing or selecting something.
- (perhaps) click a value in table to make it a filter?
- Ability to add something to the filter set
- Ability to remove something from the filter set
- Ability to remove all filters and show all data.
- Ability to shorten/extend date range

**Comment by foucault-dumas** [comment]
information (legend) on what the numbers represent on the x-axis should be added
<img width="772" alt="image" src="https://user-images.githubusercontent.com/81250365/155139905-6903399b-1925-464b-9575-8955644c4c50.png">
