### ISSUE TITLE
FileExplorer: some elements of the viewer stay over the navigation drawer

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#407]
In the file explorer, when we open the navigation drawer, it happens that some elements of the right panel stay visible.

Example: open a CSV, then open the navigation drawer. The headers of the table appear among the files.

![Screenshot_20211222_095713](https://user-images.githubusercontent.com/25420002/147065666-83820d04-12d2-4725-8b51-381f3aa952d6.png)

**Comment by alexbfree** [comment]
Good that you have spotted this bug. @pdehaye and I noticed this in a deep dive but didn't manage to capture a screenshot.
