### ISSUE TITLE
Investigate how we can guarantee the Kdrive drop page appears in English

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#412]
During a deep dive with a Finnish participant on Friday, he clicked the "drop file here" link after selecting files within the Share with Digipower form and the Kdrive UI appeared in French.

Please investigate how the Kdrive drop page determines its language, and more importantly if there is some way to specify a parameter on the URL to force the UI to appear in English.

**Comment by ffsinger** [comment]
Ah that's annoying, it seems that the language on this page is determined through HTTP headers. The browser sets them automatically from your settings. So if the participant has its main language to Finnish, and English is not set as a secondary language, the website doesn't know what to do and returns the default (which is apparently French in this case...).

The rest of the website allows us to set a language in the URL but not this page

**Comment by alexbfree** [comment]
Thanks for investigating.

> English is not set as a secondary language

How would someone do that? 
If we can have instructions written down for this workaround that would be useful.

**Comment by ffsinger** [comment]
In Firefox it would be like this: go to Settings -> General -> Language

There you have two buttons, one for setting the language of the menus and one for setting the language on the webpages. Click on the second one, "Choose"

![Screenshot_20220107_103617](https://user-images.githubusercontent.com/25420002/148524093-31825b1c-46b7-4bfa-8f9f-7619e599eeae.png)

A dialog opens and you can add [en] or [en-us]

![Screenshot_20220107_103708](https://user-images.githubusercontent.com/25420002/148524316-f3b5540b-e630-45bd-8dc1-547fa9384e57.png)

**Comment by fquellec** [comment]
Not relevant anymore with the bubble server
