### ISSUE TITLE
Better support for small desktop browser screensize

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#413]
When viewing the Twitter experience with a participant who had a relatively small screen resolution they could not fit the whole pie chart on screen due to the white bar at the top. I tried to replicate this afterwards, I guess their resolution was probably something like 1024 x 768? it looked something like this:

![Screenshot 2021-12-22 at 11 30 20](https://user-images.githubusercontent.com/1473244/147086461-fb7bdc82-bf57-4039-bd6e-a297cda1edcb.png)

It made me realise that the title bar wastes a lot of unnecessary screen space. Can it collapse down to perhaps just a small home icon in the top left corner once you scroll down? (and maybe reappear when you scroll to very top?) It is very big serves no useful purpose.

**Comment by fquellec** [comment]
A temporary solution for small resolutions, you can decrease the zoom level in your browser options, it will display well.
<img width="1440" alt="Capture d’écran 2022-01-20 à 10 58 16" src="https://user-images.githubusercontent.com/17878016/150316684-53fd46a2-4cc0-469a-8856-326491db2ea7.png">

**Comment by alexbfree** [comment]
generally need to make app more mobile friendly. backlog.

**Comment by alexbfree** [comment]
see #1077
