### ISSUE TITLE
Consent not being recorded properly when files are shared

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#417]
This serious bug needs fixing urgently.

In this case the participant shared selected files but none of the experiences. However the fact they consented files, and importantly the list of which files were consented, does not seem to have been recorded and is not displayed as ticked, only the number of files. You cannot click the 15 to see which files were consented.

![Screenshot 2021-12-22 at 12 15 30](https://user-images.githubusercontent.com/1473244/147091435-59591a55-501f-4112-b3e1-81a23bc61cc6.png)

consent.json:
```
[{"title":"SHARE MY #DIGIPOWER DATA","description":"With this form, you can register your consent, and optionally share additional data, in line with the SITRA #digipower contract. Please enter your name:","type":"input","name":"Name","value":"XXXX XXXX"},{"title":"WHICH DATA SHOULD BE SHARED?","description":"Data underlying the following visualisations will be shared. Select all that you want to share.","type":"data","required":true,"titles":["Dated observations","Location observations"],"keys":["genericDateViewer","genericLocationViewer"],"includedResults":[]},{"title":"FOR WHAT PURPOSE?","description":"On a strictly need-to-know basis, I consent to sharing this data for the following purposes. Select all that apply:"},{"description":"<b>Within your individual bubble (Paul and Alex only):</b>","type":"checkbox","options":["To help analyse/understand the data","For help with producing screenshots, tweets, videos or summaries (add details below if needed)","Other reason (add details below)"],"selected":["To help analyse/understand the data","For help with producing screenshots, tweets, videos or summaries (add details below if needed)"]},{"description":"<b>With Hestia.AI but not SITRA (my data will be deleted within two weeks):</b>","type":"checkbox","options":["To report a bug or issue with data extraction, display or visualisation","To help Hestia.AI developers to improve the data viewing experience","Other reason (add details below)"]},{"description":"<b>With other Participants:</b>","type":"checkbox","options":["To enable conversations and co-ordinated actions with other participants, in the precise ways I define below","Other reason (add details below)"]},{"description":"<b>Within the wider bubble between Alex, Paul and SITRA:</b>","type":"checkbox","options":["For reference by Paul and Alex while drafting public #digipower reports which I can approve/review later before they become public","Other reason (add details below)"]},{"title":"ADDITIONAL DETAILS & COMMENTS","description":"If you have anything to add, please type it here:","type":"multiline","placeholder":"e.g. particular requirements about how the data should be handled (which data, what specific purpose, any sensitivities, who should/should not be able to access it)."}]
```

**Comment by alexbfree** [comment]
Addendum: The files ARE present in the zip, so we have not lost data (Phew). but this should be properly logged and displayed.

**Comment by ffsinger** [comment]
Oh, I know what happened. The export was done when the "Select files" option was not yet a checkbox. Now that this has been updated, the page doesn't find the tick and thinks that the element was unchecked.

So there's nothing to fix for more recent forms. If it's confusing for you, I can write some compatibility code to automatically check this box if files are present.

**Comment by alexbfree** [comment]
@ffsinger sorry for delayed reply. Yes, please make sure the checkbox displays correctly. But it's more than the checkbox: 

When you load an export into the import page, there needs to be a way to click the "15 files" and see a list of which files were exported/are present (similar to the way you click during sharing to access the file select dialogue but this time could be a simple read only bulletpoint list in a popup). I guess this info is present within the `files` folder but should be surfaced more clearly on the UI.
