### ISSUE TITLE
Access manifest from vuex instead of using props

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#451]
Manifest options should not be passed down as props but it is preferred to access the current manifest from the vuex store. I think initially they were passed down as props before we started using vuex.

[Source of bad habit](https://github.com/hestiaAI/hestialabs-experiences/blob/4631143e3ab9eea5282f69f7ea1a090c871275c0/pages/_key.vue#L17)

**Comment by ffsinger** [comment]
I agree. This will be a big refactoring though
