### ISSUE TITLE
Make our full respect for privacy clear

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#458]
Several users of our experiments ([TFAC](https://trackingfreeads.eu), [Picasoft](https://picasoft.net)) give this feedback: "what you do (or don't do) with the data is not clearly written"

So we need to add on each "open access" page: "No data is transmitted to HestiaLabs or anyone else. The whole experience takes place locally in the browser and nothing is left behind as soon as you close the tab."
Where? Between the "Drop files here or browse files" box and the purple footer?

This paragraph disappears in favour of another one, which can be configured, in the export module on the pages presenting an export module. Default text: "By filling this form, I consent to add my results from this experiment to the data pools of the data collectives of my choice (to be selected below) for the exclusive purposes defined by those collectives. For more information, please see our [privacy policy](https://hestialabs.org/en/legal/).
Data collectives I choose to share my data with
- [ ] #Digipower - Purpose: To improve understanding of digital services (algorithms and data use)
- [ ] The Eyeballs - Purpose: Transparency of our attention monetisation (media, social networks, online advertising)
- [ ] Dating Privacy - Objective: Restore trust in dating services (whistleblowing, mapping of data use, best practice proposals)
- [ ] Mobility - Optimising mobility and intermodality services by and for users
- [ ] VTC Drivers and platform workers - Taking back control of their activity by taking control of their data

I understand that my results are shared nominally or anonymously depending on whether I have completed the name and email fields above."

Food for thought: in a future to be defined, this customisable export module should also appear in Ad Radar.

**Comment by ffsinger** [comment]
About the new checkboxes in the export module:

Should it appear on all the current instances (experiences, digipower, tfac) ? I'd be a bit surprised if we want to involve the digipower participants with all these collectives.

**Comment by ffsinger** [comment]
Also note that the process of data export (consent form, filedrop) is not yet defined for the `experiences` instances

**Comment by fquellec** [comment]
When there is no consent form the following message is displayed before the upload: 
> No data is transmitted to HestiaLabs or anyone else. The whole experience takes place locally in the browser and nothing is left behind as soon as you close the tab.

When there is a consent form we display the following: 
> Unless explicitly consented in the "Share My Data" tab, no data is transmitted to HestiaLabs ....

Each bubble or instance can then define a custom data privacy policy in their consent form.
