### ISSUE TITLE
UX improvement for Summary - Overview Tab

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#466]
Now that we have separate tabs, I propose we move the Summary text (list of files/types etc) into its own tab, the first tab, called "Overview"

This will have the advantage of saving screen space within the file explorer/file details view, and provide a simple overview of data that is always present on first tab. This tab should be the first one shown after processing.

Also I think this may make it easier to implement clickable filenames as they would just switch tab focus onto file details panel with a particular file loaded.

**Comment by alexbfree** [comment]
Good but I would like to do this anyway, saving space is not the only reason to do it.

**Comment by alexbfree** [comment]
We discussed this in standup today. I recognise not all the devs are convinced of the value but I think it is an important first step towards simplifying the UX around file previewing/selection/navigation. It should go ahead.

**Comment by streitlua** [comment]
This should be done as of #482.
