### ISSUE TITLE
Show which files are expected in each experience - and show what's wrong when mismatched.

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#480]
Standalone feature that will allow other tickets such as #353 to be done later.

Each experience should communicate to user which files it is expecting WITH EXACT PATH info.
This info needn't be on screen all the time (either collapsible side panel or popup from an (i) icon)
It is most needed at the dragging file/just about to press Process Files stage.

The task is to (a) develop the feature to show such info on screen
(b) to go through all experiences and map whatever internal specification/files to check for list - and expose that into the feature - so that the experience user can now precisely what paths/files are being looked for.

Also: When a file is not found. please show what WAS found.

e.g. 
```
expected:
data/ad_impressions.js
but found
twitter-username/data/ad_impressions.js
```
The idea here is not to do anything clever like in #353 - just show what we expect, and when not found, list alternative locations of those files that are present, with the goal of helping the user to fix their zip structure, (even if the need to do that is ultimately superseded by #353).

While #353 may take time/be blocked, this ticket should move ahead faster to give us a better UX right away while we wait for a longer term fix.

**Comment by alexbfree** [comment]
As discussed in standup today, even tho #353 has been addressed, we still want this info available as it is good UX for users.

We realised in standup discussion that two things are needed
- at upload time, information to help you decide what is worth uploading
- on specific views, information about which files are needed/used/being included in that view

**Comment by alexbfree** [comment]
Confirmed working nicely on digipower

**Comment by alexbfree** [comment]
wait, that might have been premature. will reopen for now

**Comment by alexbfree** [comment]
In Google experience, I see this, which is not right:

<img width="600" alt="Screenshot 2022-01-27 at 16 52 52" src="https://user-images.githubusercontent.com/1473244/151405893-56ca7491-a9cd-4430-9765-3a43667ccbb4.png">

**Comment by alexbfree** [comment]
Also in Google experience, I have one dataset where I am getting this. I am not getting any information on why the data is not being found. I have checked and it is definitely JSON data files present - must be some other reason. 

<img width="974" alt="Screenshot 2022-01-27 at 16 49 27" src="https://user-images.githubusercontent.com/1473244/151405985-0ef3593b-4d9d-4d6b-b2dc-24be0c782be7.png">

In general, "No relevant data found" should provide more detail - for Google and maybe for others. Reminding the user when they have provided HTML instead of JSON will be especially useful - but also, when the file expected is simply absent. Or when no timestamped data was found across N files, or no location data was found across N files, we could tell the user just a little more about where we looked and what we didn't find.

**Comment by alexbfree** [comment]
Also, is there a plan for 

> on specific views, information about which files are needed/used/being included in that view

**Comment by ffsinger** [comment]
> EDIT: Maybe this IS done, just not for Google?

Yes it's done for the other experiences (look at Twitter, Facebook, Uber), but Google is a special case that I didn't consider (the "My activity information" experience looks at all the files satisfying this regex: `(?:.*/)?(.+?)/(?:OmatTapahtumat|MonActivité|My Activity)\\.json`

> Also in Google experience, I have one dataset where I am getting this. I am not getting any information on why the data is not being found. I have checked and it is definitely JSON data files present - must be some other reason.

Do your files match the regex above ?
