### ISSUE TITLE
Current search column filtering design is problematic when there are a lot of fields

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#491]
Example (takes up whole screen!):

![Screenshot 2022-01-17 at 09 27 53](https://user-images.githubusercontent.com/1473244/149743587-301c173b-21c8-4610-a72f-4452bb9c48db.png)

any suggestions?

**Comment by fquellec** [comment]
This should be fixed with https://github.com/hestiaAI/hestialabs-experiences/issues/370
Working on it now !

**Comment by valentinoli** [comment]
![image](https://user-images.githubusercontent.com/23453691/149744822-75ea244c-d775-436e-85c8-303783c0bbfa.png)

**Comment by fquellec** [comment]
This should work just fine @valentinoli  but I'm working on an improved solution for column filtering. Currently, it is not possible to apply multiple filters to the table.
![image](https://user-images.githubusercontent.com/17878016/149745592-8dd4eee5-e452-4566-bdc3-16bdb8be37cb.png)

**Comment by valentinoli** [comment]
Ah ok :)

**Comment by alexbfree** [comment]
Waiting until #370 is closed
