### ISSUE TITLE
What doubled the build time?

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#494]
Investigate why the netlify build jumped from [**4m45s**](https://app.netlify.com/teams/hestia/builds/61c2ded881c9700008348d20) for d24bb24a56 
```
9:17:30 AM: $ npm run build
9:17:30 AM: > hestialabs-experiences@1.0.0 build
9:17:30 AM: > npm run build:static
9:17:30 AM: > hestialabs-experiences@1.0.0 build:static
9:17:30 AM: > nuxt generate
9:21:10 AM: ​
9:21:10 AM: (build.command completed in 3m 40s)
```

to [ **10m25s**](https://app.netlify.com/teams/hestia/builds/61d5564bc8f0860009b511d9) for 1f56f71bd21f5

```
9:28:23 AM: $ npm run build
9:28:23 AM: > hestialabs-experiences@1.0.0 build
9:28:23 AM: > npm run build:static
9:28:23 AM: > hestialabs-experiences@1.0.0 build:static
9:28:23 AM: > nuxt generate
9:37:10 AM: ​
9:37:10 AM: (build.command completed in 8m 47.1s)
```

Do we see the same difference when we run it locally? 

Can we isolate a commit where build times jump (try git bisect)? 

Is it some new library we're using?

**Comment by andreaskundig** [comment]
The build sometimes [fails](https://app.netlify.com/sites/digipower/deploys/61e7eab62008f4000740b4ff), probably because netlify kills it when it's using to much ram.

**Comment by andreaskundig** [comment]
Local build time for `time BASE_URL=ak npm run build` on my machine

- 1f56f71 5m39
-  d24bb24 3m07

**Comment by andreaskundig** [comment]
The first bad commit is a squashed commit from another branch made for pull request  #341:  feat/web-share-api 

- 8d457c36aee208dcc2 (last one on the branch)
- ab99077 5m6.735s
- 7439c9d
- 8a2c39b broken
- 85ebb43 broken
- bb397da broken
- bcb8619 broken
- c23bd44 2m46.815s
- 5d0b7ae 2m36.271s
- e186e300230a07ff  3m3.733s

**Comment by valentinoli** [comment]
@andreaskundig I think the broken commits are a result of me messing with the `package-lock.json`. [Florian pointed it out to me](https://github.com/hestiaAI/hestialabs-experiences/pull/341#pullrequestreview-835267154). I fixed it in https://github.com/hestiaAI/hestialabs-experiences/commit/7439c9d689f318e18d28a7a84ee923cb529afb3e

**Comment by valentinoli** [comment]
In commit https://github.com/hestiaAI/hestialabs-experiences/commit/fc55b5c4a070763d5a1b98fcbbccf316384ab52f I removed 1 library (`vue-social-sharing`) and added 2 (`dom-to-image-more` (4 MB unpacked) and `share-api-polyfill` (1 MB unpacked))

**Comment by andreaskundig** [comment]
We should investigate how to make nuxt generate run faster, and try out some these [tips](https://www.voorhoede.nl/en/blog/10x-faster-nuxt-builds-on-netlify/#optimise-html-minification)

**Comment by valentinoli** [comment]
All SPARQL/RDF related libraries have been removed

**Comment by alexbfree** [comment]
close
