### ISSUE TITLE
Ensure that media files are ignored and to avoid delay/crash when uploading large files to Twitter experience

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#495]
(this is a blocking issue for Twitter experience)

With a participant today, we uploaded a 400Mb Twitter zipfile (returned from SAR). which contained 388Mb of media files (the entire contents of the `assets/images` and `data/tweet_media` directories)

Because the file was so large, the experience did not respond in a reasonable time (crashed?)

Please update the code so that these directories are ignored for Twitter uploads. Optionally a count can still be shown in the summary as 'suppressed/hidden' if this is easy to do but mainly the goal is to ensure that the analysis of large Twitter zipfiles are not slowed down by files we can't do anything with anyway.

It may also be worth considering how in future we might generalise this problem to filter out media files for other experiences.

**Comment by alexbfree** [comment]
yes i can reproduce the issue (maybe it's a different issue). Not a hang this time. after a LONG wait I get..
![Screenshot 2022-01-17 at 13 43 48](https://user-images.githubusercontent.com/1473244/149779863-5dfaebf4-ab99-47db-ac1b-a29b0d9a89a3.png)

**Comment by alexbfree** [comment]
As you can see, the file is definitely present

![Screenshot 2022-01-17 at 13 45 20](https://user-images.githubusercontent.com/1473244/149779971-d39d5b1a-e1d6-4c8c-a16d-15c13c0fd19f.png)

**Comment by alexbfree** [comment]
I tried various zipping options in case this is just the problem #353 describes. But no joy.

**Comment by alexbfree** [comment]
i am not able to share the data (yet) but can run it on my machine to help testing.

**Comment by ffsinger** [comment]
The folder `twitter-2021-12-13-b977...` shouldn't be in the zip. `data` needs to be at the root when you unzip

But if you already tried this, do you have any other error message in the console ?

**Comment by alexbfree** [comment]
Hmm this is how it came. Maybe it's that some browsers zip it for you upon download?

OK you are right. I rezipped it differently and that worked. 
So this IS just another instance of #353 's problem then. Ugh.

**Comment by alexbfree** [comment]
OK so assuming this will be addressed by #353 and #480, I am closing.

**Comment by alexbfree** [comment]
Incidentally we have now had 2 participants share their twitter data in this format of twitter-YYYY-{longID}/data/ subdirs so I guess the format they deliver in has changed? (or maybe different for SAR vs download portal). Anyway, this shouldn't matter once #353 is done.
