### ISSUE TITLE
In bar graphs where the long tail of disparate items are grouped, need option to show/hide the long tail

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#503]
For example:

<img width="498" alt="Screenshot 2022-01-18 at 15 47 40" src="https://user-images.githubusercontent.com/1473244/149970756-ad9c6636-3453-4ab6-849f-ab6102da4365.png">

On this graph, we need an option to hide "All Others" so the other bars can be viewed in a meaningful way.

**Comment by fquellec** [comment]
This one have have been fix in https://github.com/hestiaAI/hestialabs-experiences/pull/436
It was not deployed but it is now!

**Comment by alexbfree** [comment]
Can you note down what has been added?
