### ISSUE TITLE
Unify the UI of the application

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#511]
The application is made up of a large number of elements that were not meant to be displayed as they are now. We should take the time to unify each component of the user interface to something meaningful overall. For example, each sub-experience sheet was displayed in a list before and now in tabs, it seems a bit odd to have tabs with different heights.

I'm not going to list all the UI/UX issues here but rather send you some before/after screenshots to be discussed in this issue

**Comment by fquellec** [comment]
First proposal: 
- make the whole experience page as tabs
- remove the shadow effect from the sub-experience cards
- display the newsletter as a disposable alert (and in the footer)
- make the share button at a fixed position. 
We still need to find a way to display the title of the experience (Netflix, Twitter, ...).

Demo: 
![image](https://user-images.githubusercontent.com/17878016/150355507-1116a6c1-ca49-416e-910e-e63aaef9f8fe.png)

**Comment by alexbfree** [comment]
This looks great. Happy for this to be worked on as priority 2. :-) Sounds like it is nearly done.

**Comment by alexbfree** [comment]
I agree with @ffsinger that it should not be called upload. I suggest "Load your Data"

**Comment by alexbfree** [comment]
> We still need to find a way to display the title of the experience (Netflix, Twitter, ...).

If you haven't already solved this, I propose putting it where the "Analyze your private data" title is.
That title could change to e.g. "Analyse your Netflix data" with Logo just to left of title.

**Comment by fquellec** [comment]
How about putting the title and logo of the experience in the top bar? That way we would always know which experiment we are in!
![image](https://user-images.githubusercontent.com/17878016/150509884-37bc878c-9a01-4564-a799-cc174864a5a6.png)
