### ISSUE TITLE
Need ability to find/jump to text in JSON tree without filtering; and more generally need to distinguish find/search/filter better across experiences.

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#513]
A small UX thing I noticed in Deep Dive today. When you search for a text string in the JSON tree, we filter down to show *exactly* the matching node, and nothing else. However - in most cases the search string is just something to get you to the right row/record/vicinity. Therefore we are filtering out information that the user actually wants to see.

Probably what we should do when filtering the tree is show all items that are in the tree anywhere above the matched node. (including siblings, parents, grandparents, siblings of parents, siblings of grandparents, etc)

Perhaps we need a toggle to show/hide related nodes for each match.

I suppose thinking about it, in a tree format, a search (ie. ability to jump to a point in the tree) is more valuable than a filter (show only matching nodes).

**Comment by alexbfree** [comment]
Comments from @andreaskundig (from Signal):

> I just asked Florian about the problems he encountered when first implementing this and you are right that it requires careful thought. If we just open all nodes that match it will be too heavy if all nodes of a big file match. @ffsinger thinks we need a way to show only a few and navigate to the next. It's not obvious how this should look. Let's put comments about this on the issue

And from @alexbfree :

> Yes, probably needs a little discussion as there are several options. Generally, i think we probably need to be clearer across our experiences about the differences between Search and Filter. they are not the same

**Comment by alexbfree** [comment]
@andreaskundig sorry I edited my comment just after you thumbs-upped. might need a refresh to see latest addition

**Comment by andreaskundig** [comment]
(it updated nicely without a refresh)
