### ISSUE TITLE
Improve Twitter experience to allow filtering by follower-lookalike / advertisers and move between the two

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#514]
In the same way we can move between Tracked Apps and Targeted Advertisers on Tracker Control experience, we need to be able to do something similar on Twitter.

example scenario:

1. select a specific follower lookalike (maybe from lookalikes tag cloud or 1-advertiser-pie-chart)?
2. jump to the "Twitter advertising overview" but we are now filtering on only this follower lookalike (across all data). Alternatively there is a way to directly filter on a lookalike within Twitter advertising overview
3. can now pick on a specific advertiser that is targeting based on this follower lookalike from list and filter on that. Now we see only data for this lookalike-advertiser pair
4. now we can remove the original follower lookalike but still locked onto the advertiser and that is now the filter in effect - can see all lookalikes they used.

Other scenario would be 2-to-4 the other way round, starting with advertiser, then picking lookalike, then removing advertiser.

Possibly best way to do this is another graph onto the Twitter advertising overview (this would address 2-to-4 and 4-to-2).
I realise the jump described in step 1 are new - but would be useful if possible. That part is nice to have. Priority is to be able to do 2-to-4 and 4-to-2 via Twitter Advertising Overview.

We could also consider a new separate view for this. But that may be overkill.

**Comment by alexbfree** [comment]
@pdehaye Hopefully this captures what we said. Please comment if you want any changes to the spec.

**Comment by alexbfree** [comment]
@foucault-dumas you may wish to comment as well as this will be useful for TFAC

**Comment by foucault-dumas** [comment]
The narrative could be important and is not taken into consideration in our experience.
Potential partners are interested in who is targeted by a particular narrative --> see the promoted tweets and take them as an entry point for a sum of data sets —> this promoted tweet was shown to w, y, z = X persons (x%) in our sample of people, using this and this criteria.

**Comment by alexbfree** [comment]
I see this has been Production Deployed. Could someone just summarise what is now available and where?

**Comment by fquellec** [comment]
I have added a search function in the Twitter overview for targeting criteria, advertiser and targeting value. This allows every interaction described in this issue.
