### ISSUE TITLE
Is sorting in tables working correctly across experiences?

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#515]
I noticed that the sorting (e.g. by date) in tables by clicking the table header/sort arrow seems to sort only those rows that are currently on screen? Not all the rows of the source data? 

It should sort the source data and re-retrieve the correct rows for the current dropdown setting:

If dropdown is set to show `N` rows show:

-  earliest `N` rows [if date ascending]
-  most recent `N` rows [if date descending] 
- first `N` rows [if date sort removed or never set]

moving to next page from this point should traverse the sorted source data maintaining same sort setting.

This logic of course should apply to all column sorts not just dates - that is just an example.

**Comment by ffsinger** [comment]
For me it works fine, and this sorting feature is provided by an external library, I'd be surprised if there was such a bug. Do you have a specific example ?

**Comment by alexbfree** [comment]
To be fair, I can't reproduce this any more. I definitely saw it a couple of weeks back. I had 5 rows on screen from 2013 but the dataset contained some from 2018, sorting both ways didn't reveal the 2018 rows, had to use the dropdown to show all. Since I can't reproduce this now, will close.
