### ISSUE TITLE
Recognise browser back button

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#530]
As an example, when you click on a file in the Summary tab, and press back, it doesn't go back to Summary, but to whatever you were viewing before the #digipower site. Can we make the back button work and go back to whatever tab / experience page you viewed last?

**Comment by valentinoli** [comment]
Yes, it is possible

**Comment by valentinoli** [comment]
I'll do it

**Comment by valentinoli** [comment]
Should be fixed in #535
