### ISSUE TITLE
Cookies created by share button

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#542]
When clicking on the share button, two cookies with ominous names are created:

- `MicrosoftApplicationsTelemetryFirstLaunchTime`
- `MicrosoftApplicationsTelemetryDeviceId`

This may affect the trust of more advanced users. We should investigate if it's possible to block these cookies.

**Comment by valentinoli** [comment]
@ffsinger Which share button are you referring to?

**Comment by ffsinger** [comment]
![Screenshot_20220131_140851](https://user-images.githubusercontent.com/25420002/151799325-cc417902-1352-4694-ab4a-80e149beedd8.png)

**Comment by valentinoli** [comment]
Can't see these cookies on my side🤔
And I didn't implement them and the Web Share API doesn't require any cookies

**Comment by ffsinger** [comment]
I triple checked and it does appear on my side, here's what I get when I click on the button:

![Screenshot_20220202_192525](https://user-images.githubusercontent.com/25420002/152215055-e285b6b7-8b13-4378-a5ad-85cc25caafdb.png)

I did some research and couldn't find anything about these cookies :/

**Comment by valentinoli** [comment]
This is super weird, thanks for checking @ffsinger. Can you tell me if the native sharing window appears or the polyfill window?

**Comment by valentinoli** [comment]
I tried searching for `MicrosoftApplicationsTelemetryDeviceId` on GitHub

Search results within entire GitHub:
https://github.com/search?q=MicrosoftApplicationsTelemetryDeviceId

Search results within the microsoft organization on GitHub:
https://github.com/search?q=org%3Amicrosoft+MicrosoftApplicationsTelemetryDeviceId

**Comment by ffsinger** [comment]
It's the polyfill

Since these cookies seem to be related to Skype, I noticed that the HTML of the polyfill window contains a button for Skype, but it's the only button that doesn't appear on my page.

![Screenshot_20220203_120002](https://user-images.githubusercontent.com/25420002/152330342-2aac3b58-29a2-48e7-8fa9-fe61c298775f.png)

With my limited understanding of how this share API works, my hypothesis is that
- The polyfill tries to include a share option for skype, through an API provided by skype (the previously mentioned `shareButton.min.js`)
- This API is trying to set some cookies for telemetry, but it's blocked by the browser

**Comment by valentinoli** [comment]
The polyfill doesn't use the Web Share API, that's why it's called a polyfill :)
So this explains a lot, thanks for the research - this would explain the cookies. What we can do is to set `skype: false` to [this line](https://github.com/hestiaAI/hestialabs-experiences/blob/ee6d1016c31ae6e7b68c449a66f605710aa1f205/components/base/button/BaseButtonShare.vue#L155) to disable Skype sharing

**Comment by valentinoli** [comment]
@ffsinger I tested on Firefox (where the polyfill kicks in) and it works

Thanks again for this issue
See this comment in the [polyfill repo README](https://github.com/on2-dev/share-api-polyfill/blob/main/README.md#turning-features-off-in-desktop):

> If you disable Skype, it will no longer load Skype's SDK, what might be something you want, in case you would like to improve the privacy in your project, avoiding loading third party libraries.

**Comment by ffsinger** [comment]
Thanks for the fix ! I'm glad we were able to solve this
