### ISSUE TITLE
Subdomain and redirect changes

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#543]
Just to capture what we said in standup today:

1) Please change existing https://digipower.hestialabs.org address to point to the site which is currently at https://data-stories.netlify.app/
2) Please set up https://digipower-experiences.hestialabs.org address to point to the site currently at https://digipower.hestialabs.org
3) Please set up redirects on new digipower.hestialabs.org (temporary: 302 NOT 301 as I said previously) to redirect the links getting traffic from [Mark Scott's article](https://www.politico.eu/newsletter/digital-bridge/russian-disinformation-me-myself-and-my-data-digital-tax-difficulties/) to go to the experiences:
https://digipower.hestialabs.org/twitter => https://digipower-experiences.hestialabs.org/twitter
https://digipower.hestialabs.org/google => https://digipower-experiences.hestialabs.org/google
https://digipower.hestialabs.org/facebook => https://digipower-experiences.hestialabs.org/facebook
4) Please check the user experience after this is done - ideally clicking back to homepage and other experiences doesn't take you out of https://digipower-experiences.hestialabs.org
5) Could you outline current thinking around experiences.hestialabs.org (might want to use that subdomain for the digipower experiences in future). No action to be done here just for future planning.
6) Please also capture/write down what issues/challenges we would face if at some point in future we want to merge experiences and data-stories into a single website, along with any recommendations (the issues around CMS saves generating a build etc)

**Comment by andreaskundig** [comment]
The redirects are configured in a file called [netlify.toml](https://github.com/hestiaAI/hestialabs-experiences/blob/master/netlify.toml) at the root of the project. Here's [netlify's documentation](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file) about that
