### ISSUE TITLE
Feature: Add Tutorial videos on experiences

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#605]
We want a way to add tutorial videos on certain experiences to explain to the user how to get their data or use the tool. The videos are hosted on Vimeo. Links to the videos should be added to the JSON manifest. Contact @foucault-dumas for examples. 
DEMO: 
![image](https://user-images.githubusercontent.com/17878016/161501980-7c579e92-cf1b-467b-91b8-34d693f775cf.png)

**Comment by valentinoli** [comment]
@fquellec can it be closed? does it need testing?
