### ISSUE TITLE
Issues with Google Experience

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#621]
When trying to upload a participant's Google SAR response (unusual, usually we only have Takeout files) I hit two issues:

1. No access to file viewer within Google Experience? (necessary in SAR case)

2. In original format, there was a zip within a zip, this caused an error:
(was able to fix by unzipping inner zip then rezipping - ideally shouldn't have to do this)

<img width="621" alt="Screenshot 2022-04-12 at 11 25 44" src="https://user-images.githubusercontent.com/1473244/162940511-aaf709e4-c1e8-41d9-9d9e-c7fb74369939.png">

**Comment by alexbfree** [comment]
well ok that's news to me. i though we were doing 1 experience per company

**Comment by alexbfree** [comment]
If the experience is only for Google Takeout we should label it as such to avoid confusion.

**Comment by alexbfree** [comment]
Also, issue 2 still occurs in the Generic experience, so still needs fixing

**Comment by valentinoli** [comment]
@alexbfree how about setting the subtitle of the Google experience to `Google Takeout Experience` ?

**Comment by valentinoli** [comment]
Or we could just change the main title to `Google Takeout` and/or change the icon

![image](https://user-images.githubusercontent.com/23453691/162952198-1d2a5ff5-2144-45db-9464-4abf34fe20c5.png)

**Comment by valentinoli** [comment]
> 1. No access to file viewer within Google Experience? (necessary in SAR case)

Caused by the following lines
https://github.com/hestiaAI/hestialabs-experiences/blob/4043d8f999ef07b376b16782b70ba98ed734900a/manifests/experiences/google/google.json#L6-L7

They were added 20 days ago by @fquellec as a response to #582 in PR #583
