### ISSUE TITLE
Filtering Location Map [Facebook experience]

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#630]
Not sure if this is a bug or feature request, probably the latter... when you filter the table below the map in Location Observations, it would be great if the map redraws to only plot the points that show in the table. (would allow me to tell which locations on map are coming from exif data vs from location history)

Saw this in Facebook experience but it may apply everywhere.

**Comment by valentinoli** [comment]
Done according to @fquellec
