### ISSUE TITLE
TikTok experience

### ISSUE THREAD

**Issue by mvidonne** [hestiaAI/hestialabs-experiences#668]
@fquellec or @valentinoli 
Please add this link https://support.tiktok.com/en/account-and-privacy/personalized-ads-and-data/requesting-your-data for the TikTok experience

and the sentence Click here to request the private data that TikTok collected on you. Once you receive it, analyze it here.

**NEED to mention also that the user needs to ask for the JSON format**

**Comment by valentinoli** [comment]
@fquellec

**Comment by valentinoli** [comment]
https://github.com/hestiaAI/hestialabs/commit/b93e5da631dbf3c8430eae3e09e474d286923477
