### ISSUE TITLE
Fitbit experience

### ISSUE THREAD

**Issue by mvidonne** [hestiaAI/hestialabs-experiences#670]
@fquellec or @valentinoli

Could you please add this link: https://help.fitbit.com/articles/en_US/Help_article/1133.htmfor the Fitbit experience.

and add this sentence Click here to request the private data that Fitbit collected on you. Once you receive it, analyze it here.

@alexbfree  do the user need for a specific file format? i.e json??

**Comment by valentinoli** [comment]
Done, just need to know the answer to the file format question. Re-assigning to @fquellec

**Comment by valentinoli** [comment]
https://github.com/hestiaAI/hestialabs/commit/b93e5da631dbf3c8430eae3e09e474d286923477
