### ISSUE TITLE
"ERROR  Rule can only have one resource source"

### ISSUE THREAD

**Issue by emmanuel-hestia** [hestiaAI/hestialabs-experiences#675]
I keep getting an 
"ERROR  Rule can only have one resource source"
problem when starting "npm run dev". 

This happens whatever version of node and npm I use (nominal versions are npm: '7.24.2', node: '14.19.2').

The complete error message looks like this:

>  ERROR  Rule can only have one resource source (provided resource and test + include + exclude) in {                                                                                                                                           12:25:01
>   "use": [
>     {
>       "loader": "/home/rama/Documents/hestia/dev/hestialabs-experiences/node_modules/babel-loader/lib/index.js",
>       "options": {
>         "configFile": false,
>         "babelrc": false,
>         "cacheDirectory": true,
>         "envName": "client",
>         "presets": [
>           [
>             "/home/rama/Documents/hestia/dev/hestialabs-experiences/node_modules/@nuxt/babel-preset-app/src/index.js",
>             {
>               "corejs": {
>                 "version": 3
>               }
>             }
>           ]
>         ]
>       },
>       "ident": "clonedRuleSet-4[0].rules[0].use[0]"
>     }
>   ]
> }
> 
>   "use": [
>   {
>   "loader": "node_modules/babel-loader/lib/index.js",
>   "options": {
>   "configFile": false,
>   "babelrc": false,
>   "cacheDirectory": true,
>   "envName": "client",
>   "presets": [
>   [
>   "node_modules/@nuxt/babel-preset-app/src/index.js",
>   {
>   "corejs": {
>   "version": 3
>   }
>   }
>   ]
>   ]
>   },
>   "ident": "clonedRuleSet-4[0].rules[0].use[0]"
>   }
>   ]
>   }
>   at checkResourceSource (node_modules/@nuxt/webpack/node_modules/webpack/lib/RuleSet.js:167:11)
>   at Function.normalizeRule (node_modules/@nuxt/webpack/node_modules/webpack/lib/RuleSet.js:198:4)
>   at node_modules/@nuxt/webpack/node_modules/webpack/lib/RuleSet.js:110:20
>   at Array.map (<anonymous>)
>   at Function.normalizeRules (node_modules/@nuxt/webpack/node_modules/webpack/lib/RuleSet.js:109:17)
>   at new RuleSet (node_modules/@nuxt/webpack/node_modules/webpack/lib/RuleSet.js:104:24)
>   at new NormalModuleFactory (node_modules/@nuxt/webpack/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
>   at Compiler.createNormalModuleFactory (node_modules/@nuxt/webpack/node_modules/webpack/lib/Compiler.js:636:31)
>   at Compiler.newCompilationParams (node_modules/@nuxt/webpack/node_modules/webpack/lib/Compiler.js:653:30)
>   at Compiler.compile (node_modules/@nuxt/webpack/node_modules/webpack/lib/Compiler.js:661:23)
>   at node_modules/@nuxt/webpack/node_modules/webpack/lib/Watching.js:77:18
>   at _next1 (eval at create (node_modules/@nuxt/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
>   at eval (eval at create (node_modules/@nuxt/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
>

**Comment by andreaskundig** [comment]
What branch and commit are you on in hestialabs and hestialabs-experiences ? 
This [stackoverflow answer](https://stackoverflow.com/questions/64373393/error-rule-can-only-have-one-resource-source-provided-resource-and-test-incl) suggests it's a problem with webpack.

What the result of `npm ls webpack` on your machine?

**Comment by emmanuel-hestia** [comment]
Thank you!
branch "master" for hestialabs-experiences and branch "tiktok" for hestialabs

Here goes for webpack:

$ npm ls webpack
hestialabs-experiences@1.0.0 /home/rama/Documents/hestia/dev/hestialabs-experiences
├─┬ @nuxtjs/eslint-module@3.1.0
│ └─┬ eslint-webpack-plugin@2.6.0
│   └── webpack@5.72.0 deduped
├─┬ @nuxtjs/vuetify@1.12.3
│ └─┬ vuetify-loader@1.7.3
│   └── webpack@5.72.0 deduped
├─┬ @vue/preload-webpack-plugin@2.0.0
│ └─┬ webpack@5.72.0
│   └─┬ terser-webpack-plugin@5.3.1
│     └── webpack@5.72.0 deduped
├─┬ file-loader@6.2.0
│ └── webpack@5.72.0 deduped
├─┬ html-webpack-plugin@5.5.0
│ └── webpack@5.72.0 deduped
├─┬ nuxt@2.15.8
│ └─┬ @nuxt/webpack@2.15.8
│   ├─┬ @nuxt/friendly-errors-webpack-plugin@2.5.2
│   │ └── webpack@5.72.0 deduped
│   ├─┬ babel-loader@8.2.5
│   │ └── webpack@5.72.0 deduped
│   ├─┬ cache-loader@4.1.0
│   │ └── webpack@4.46.0 deduped
│   ├─┬ css-loader@4.3.0
│   │ └── webpack@5.72.0 deduped
│   ├─┬ extract-css-chunks-webpack-plugin@4.9.0
│   │ └── webpack@5.72.0 deduped
│   ├─┬ hard-source-webpack-plugin@0.13.1
│   │ └── webpack@5.72.0 deduped
│   ├─┬ html-webpack-plugin@4.5.2
│   │ └── webpack@4.46.0 deduped
│   ├─┬ optimize-css-assets-webpack-plugin@5.0.8
│   │ └── webpack@4.46.0 deduped
│   ├─┬ style-resources-loader@1.5.0
│   │ └── webpack@5.72.0 deduped
│   ├─┬ terser-webpack-plugin@4.2.3
│   │ └── webpack@5.72.0 deduped
│   ├─┬ thread-loader@3.0.4
│   │ └── webpack@5.72.0 deduped
│   ├─┬ time-fix-plugin@2.0.7
│   │ └── webpack@5.72.0 deduped
│   ├─┬ url-loader@4.1.1
│   │ └── webpack@5.72.0 deduped
│   ├─┬ vue-loader@15.9.8
│   │ └── webpack@5.72.0 deduped
│   ├─┬ webpack-dev-middleware@4.3.0
│   │ └── webpack@5.72.0 deduped
│   ├─┬ webpack@4.46.0
│   │ └─┬ terser-webpack-plugin@1.4.5
│   │   └── webpack@4.46.0 deduped
│   └─┬ webpackbar@4.0.0
│     └── webpack@4.46.0 deduped
├─┬ sass-loader@10.2.1
│ └── webpack@5.72.0 deduped
└─┬ worker-loader@3.0.8
  └── webpack@5.72.0 deduped

**Comment by andreaskundig** [comment]
hestialabs-experiences works with webpack 4, not 5. I suspect your package.json and package-lock.json are different from master. Reset them to the version in master and run `npm install`.

If you install the project from scratch by git clone and do a `npm install`, it should have webpack 4.
