### ISSUE TITLE
Change the kepler map layout to something more familiar

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/hestialabs-experiences#686]

**Comment by alexbfree** [comment]
Specifically, we need to have a white background not black. So we can use it on flyers and in screenshots easily.

For inspiration see leaflet.js/mapbox
https://leafletjs.com/

![Screenshot 2022-05-18 at 12 32 48](https://user-images.githubusercontent.com/1473244/169029298-6f0a4fc4-4637-4ad9-a01f-f77f15f06b88.png)

Paul says there is a white/black flag in Kepler so we should do that straight away as stage 1; then we can look at whether the map is familiar enough. the black ones seem to lack some detail.

**Comment by wilderino** [comment]
https://docs.kepler.gl/docs/user-guides/f-map-styles To have all info about map style
