### ISSUE TITLE
Reduce memory used by build

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#698]
The build uses so much memory that netlify frequently kills it. In this [useful post on on the netlify forum](https://answers.netlify.com/t/support-guide-making-sure-your-builds-use-appropriate-resources-for-netlifys-build-system/5349) we learn that only 3GB is guaranteed, but with some luck we can get 6GB sometimes. I think our builds only pass when we have this luck.

Webpack has some documentation about [build performance](https://v4.webpack.js.org/guides/build-performance/). 

If we can't fix the build, we'll have to build the site locally and push the result.

For some reason, the builds for experiences.hestialabs.org and test.hestialabs.org have passed more often than for digipower.hestialabs.org. Not sure if it's just a coincidence

When looking at the console during a local build, I see that memory starts climbing at
```
* Client █████████████████████████ additional chunk assets processing (90%)
```
And keeps on climbing while there are a lot of messages like this
```
* Client █████████████████████████ after chunk asset optimization (93%) SourceMapDevToolPlugin 467f89a.js
```

**Comment by valentinoli** [comment]
todo: change `source-map` to `eval` or similar for development
