### ISSUE TITLE
Bubble Authentication

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#708]
Configure Nuxt to prompt the user to authenticate for access to a bubble

**Comment by andreaskundig** [comment]
The password can be checked on the server with the REST API /bubbles/[bub-name]/authenticate
The password that allows to authenticate is also need to upload files with POST /bubbles/[bub-name]/files/[file-name]

**Comment by valentinoli** [comment]
We need to

1. Show the list of experiences available to the current bubble
2. Redirect the user to the /login page when another bubble is accessed
3. Remove the logout function (for now)
4. Highlight the current bubble in the navigation drawer and display the current bubble
