### ISSUE TITLE
Collective Google experience

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/hestialabs-experiences#711]
The size of the anonymity set n should be chosen and used as described here #719. 

PLACES VISITED:

- [x]  Places visited by at least n participants

PLACES SEARCHED: 

- [x] Places searched by at least n participants

TL BUILDING:
- [x] Mean time spent by participant in the TL building
- [x] Total time spent by participant in the TL building
- [x] Places that were the most frequently other candidates of the TL building

PUBLIC TRANSPORT:

- [x] Public transport took by at least n participant (e.g. m2)
- [x] Trips made in public transport by at least n participant (e.g. Lausanne-Flon -> Lausanne Ouchy)

MEANS OF TRANSPORT:

- [x] Colored zones depending on the activity type

WIFI:

- [x] Access points recorded by at least n participants

**Comment by alexbfree** [comment]
Idea for how to use this in workshop @foucault-dumas : start n at the max, and decrement n for as long as all in the room are comfortable to reduce it.
