### ISSUE TITLE
A way to share data experiences between websites

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#72]
Based on a discussion with Paul-Olivier and Valentin about the long term goals of the application (2012-09-01)

# Data experience menu

The landing page of this tool shows a menu of data experiences.

When adding the tool to your website, you should be able to configure what experiences to display. 

For example hestia's website could give access to all experiences, but a data collectives website would have only experiences relevant to it's topic.

# Data experiences stores

The data experiences you could add to your menu should be accessible in a store.

You could also create data experiences of your own, and make them available in your own store. Other websites could then access your store and install your data experiences in their menu.

**Comment by valentinoli** [comment]
@pdehaye @andreaskundig @alexbfree @fquellec 
closing as we've made progress in this direction
