### ISSUE TITLE
When a package is corrupted, the whole application/other packages do not load either

### ISSUE THREAD

**Issue by Amustache** [hestiaAI/hestialabs-experiences#723]
E.g., I made a typo in the block declaration of <app> in [hestialabs](https://github.com/hestiaAI/hestialabs), and nothing is loaded afterward:

![image](https://user-images.githubusercontent.com/5108539/171617237-e775fd0a-3823-427d-ba3b-83bb8e11d098.png)

Please note that:
* I did not have other tabs open (known issue).
* I did not load anything (this is the home page).
* `npm install` was correctly done (README followed).
* `npm link --workspaces` in the monorepo was not usefull (known fix).

It really gets down to "broken package => nothing works".

**Comment by valentinoli** [comment]
This is expected.

**Comment by Amustache** [comment]
> This is expected.

I believe either or both a) not applications should fail if only one is corrupted b) an explicit error should be displayed front page.

What do you think?

**Comment by valentinoli** [comment]
I think that would be ok, because anyway a package is not published unless it is error-free, so we should not expect errors in production.
But I do not know if it is technically feasible. We could try-catch around each import in `store/index.js`

**Comment by alexbfree** [comment]
closing
