### ISSUE TITLE
When using another port, Bubbles are not available

### ISSUE THREAD

**Issue by Amustache** [hestiaAI/hestialabs-experiences#742]
Minor.

e.g., when port 3000 is used and the application goes `Trying a random port...`, the Bubble server does not work.

**Comment by valentinoli** [comment]
@Amustache can you provide more details on what you did so this can be reproduced

**Comment by Amustache** [comment]
I _probably_ had an application already running on port 3000.

Hence, when the Experiences website starts, it tries to bind to port 3000, and fails, so tries to bind to another random free port.

When binding to a port that is not 3000, the Bubble servers cannot bind with the Experiences website, thus not working.

**Comment by alexbfree** [comment]
closing
