### ISSUE TITLE
The format in VS code for sql does not seem to be the correct one

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/hestialabs-experiences#748]
When I use LIMIT in sql, VS code gives me an error even though it works on the website.

**Comment by valentinoli** [comment]
I don't get an error, can you provide more details?

**Comment by wilderino** [comment]
<img width="291" alt="sql_error" src="https://user-images.githubusercontent.com/26854713/174017280-5da510d6-6800-473e-80b2-959a0fe9f461.png">

Here is the error I get.

**Comment by valentinoli** [comment]
It's an editor issue, @wilderino to be solved locally
