### ISSUE TITLE
Add a way to have parameters given to the experiences by the bubble config

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/hestialabs-experiences#808]
For example, in the Google Agg experience, the TL building tab is actually the one showing by default but I would like to have a different name for each bubble.

**Comment by andreaskundig** [comment]
The format of a config is described in [config/README.md](https://github.com/hestiaAI/hestialabs-experiences/blob/master/config/README.md). We can add new properties here. The config object is accessed by TheDataExperience.vue.

What part of the Google Agg experience needs to access it? I suppose the name you want to change is currently hardcoded. Where is it currently?

**Comment by wilderino** [comment]
In blocks.ts the TLBuilding block as the title and placeName hardcoded and it would be good to have them defined in the config
