### ISSUE TITLE
Create Brown bubble

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#891]
Create new participant bubble for the Brown group workshop on August 5th: 

- [ ] Choose and hash a password for the bubble
- [ ] Include Twitter, Facebook, Instagram, Apple Tracker, Tracker Control and Google Semantic Location
- [ ] Include bubble in digipower.academy website

Create new aggregator bubble for the Brown group:

- [ ] Choose and hash a password for the bubble
- [ ] Include TrackerControl Agg, Apple Tracker Agg, Semantic Location Agg
- [ ] Include bubble in digipower.academy website

**Comment by pdehaye** [comment]
Please also add TikTok if we have something.
Also the proper name to use is Brown-IFL.
