### ISSUE TITLE
[Modularization] Extract TheDataExperience to a module we can export on a CDN (for a client)

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#896]
I see two ways of tackling this. 

@fquellec tried the optimistic way: adding a script that builds a component to experiences' package.json and then trying to fix all the errors that appear when you run it. This way seems to difficult (branch [feat/packageExperience](https://github.com/hestiaAI/hestialabs-experiences/tree/feat/packageExperience) )

The more careful way is to create a new subproject (data-experience) that exports a component, import the component in experiences, and progressively migrate the code from experiences to data-experience, making sure that it works at every step. That's the approach taken on branch [feat/component-module](https://github.com/hestiaAI/hestialabs-experiences/tree/feat/component-module)

This *feat/component-module* now has a working example (pages/modul.vue) of importing a component with a vuex store. No code from experiences has been migrated yet.

@valentinoli and I foresee following difficulties that need to be overcome:
- refactoring the vuex store to separate the state of the nuxt app and the state of the experience (easy but requires some amount of careful work)
- refactoring TheDataExperience.vue to extract from it everything that should stay in the app (easy but some amount of careful work)
- extracting functionality done with nuxt helpers
  - vue-i18n in the component/nuxt-i18n in the app (should not be hard)
  - router (could be easy if vuetify deals with it nicely?)
  - axios and access to bubbles (should be easy)
  - maybe the authentication?
- kepler cannot be included in the library. Our integration of Kepler needs to be put in a second library.
- unforeseen difficulties should be expected (that's where the hard stuff could lurk).

**Comment by pdehaye** [comment]
What does "[to  build] a component to experiences' package.json" mean. Is it a "web component" being talked about?

**Comment by andreaskundig** [comment]
Done with #1160
