### ISSUE TITLE
Add a Tinder experience

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#90]
Excerpts from the discussion in Signal

#### Paul-Olivier:
Two changes: one additional tile in the Netflix menu of experiences, that has logo Tinder. That first change fits a pattern expected in the team already. The second change is that when opening that Tinder experience the header has, alongside the HestiaLabs logo, the Dating Privacy logo.
"the header has alongside the HestiaLabs logo, the Dating Privacy logo"

#### Andreas:
So on the landing page we will have an additional card with a big Tinder logo.

Then if you click on the Tinder card you open its experience page, where you continue to see the hestialabs logo in the app bar. Below the app bar, where the Twitter experiences have a twitter logo followed by the word "Twitter",  the Tinder experience will not have the Tinder logo, but the logo of dating privacy.

Since the logo of dating privacy already contains the words "dating privacy", I imagine you don't want to write "dating privacy" next to it?

Is it correct this time?

#### Paul-Olivier:

Not quite. Once you open the card you are on the experience page. There where you see Twitter in a different t experience you now see Tinder. The change is that where you see blank for the Twitter experiences you now see the Dating Privacy logo

#### Andreas:

Oh so this means it's a Tinder experience that was set up by the dating privacy collective, so there needs to be an additional logo to show that, for example next to the Tinder logo?

#### Valentin:

⁨(Quoting Paul-Olivier)
```
"the header has alongside the HestiaLabs logo, the Dating Privacy logo"
```
So the data experience page has the tinder logo and the heading "Tinder". And when this experience is opened the Dating Privacy Logo is appended to the app header next to HestiaLabs logo?

**Comment by valentinoli** [comment]
@andreaskundig @emmanuel-hestia I added the logo of Dating Privacy today since I was eager to implement it and it took only a few minutes :)
I did not hard code it but instead added an optional "collaborator" field to the config
