### ISSUE TITLE
Refactor BaseButton

### ISSUE THREAD

**Issue by ffsinger** [hestiaAI/hestialabs-experiences#91]
I'm observing that using the BaseButton components always consists of:

- Setting the `progress` and `status` properties
- Trying to call a function and set the `error` if it failed
- Setting the `progress` and `status` properties again

In code it gives something like this:

```javascript
handleButton() {
    this.error = false
    this.progress = true
    try {
      this.foo = f(x)
    } catch (error) {
      console.error(error)
      this.error = true
    }
    this.status = true
    this.progress = false
}
```

All this has to be managed by the parent component. If it contains multiple buttons, it quickly becomes cluttered of `progress`, `status` and `error` properties.

We should refactor the BaseButton, such that all this is managed by the button component itself.

**Comment by ffsinger** [comment]
Commit edc37893c751c591e3d4f4ff771042633e256e10 is a first draft of this. The flip side is that we now have to define the function `f` and the `args` in the parent. I'm not sure which version is better.

**Comment by valentinoli** [comment]
The purpose of the BaseButton component is just to provide a base component for buttons used in the app. Specifying that it should run a function provided as a prop when the button is clicked, showing a progress indicator, etc. is making it specific and not abstract anymore as it was intended to be. 

I like your idea but in my opinion this should be a new component that is more specific

**Comment by valentinoli** [comment]
BaseProgressButton should be used in UnitRml

**Comment by valentinoli** [comment]
I see that we have yet to replace the relevant base buttons with this new component
