### ISSUE TITLE
Add graphs to Uber driver experience

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/hestialabs-experiences#914]
Jessica asked if we could add the graphs from the client Uber experience ('ChartViewOverviewUber.vue') to the Uber driver experience (driver trips and rider trips tabs). Unfortunately, it is not easy with the multitude of formats for Uber driver. You should ask to Jessica for the most recent data-sets. 
This should be done in the uberDriver branch.

**Comment by valentinoli** [comment]
@fquellec is this done?
