### ISSUE TITLE
Decide what part of the footer is optional

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#922]
The footer currently has a lot of links to hestia, sitra, migros... 

A client might not want any of this. Do we make all of it configurable ? It could be just one field in the translation file that allows html. Do we want to have a mandatory link to hestia.ai or hestialabs.org ?

**Comment by alexbfree** [comment]
I suspect we may need to keep at least some credit to migros and/or sitra for original dev funding, see what @pdehaye says

**Comment by alexbfree** [comment]
Need to ask UFC - @pdehaye

**Comment by pdehaye** [comment]
We don't name clients on the public repos.

**Comment by alexbfree** [comment]
Need a clear statement of what should be kept + removed on what deployments.

**Comment by pdehaye** [comment]
I don't know, this will be driven by client(s), probably very last minute unfortunately as dependent on their schedule and readiness. Tagging @andreaskundig so he can flag it early too.

**Comment by alexbfree** [comment]
Andreas reports this is waiting on UFC. At which point we might add more options for footer configuration.

**Comment by fquellec** [comment]
Closing as modularization will not cover footer, if requirements change reopen.
