### ISSUE TITLE
internationalisation/globalisation issues: testing of deployment-example-experiences.netlify.app

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#932]
I am doing some testing on the deployment of code for a client that Andreas put at deployment-example-experiences.netlify.app. I will add places where I have found text in English or other issues by editing this ticket. Will add a comment when done.

**Comment by alexbfree** [comment]
Issues found in Uber experience:

Within "Vue d'ensemble" all text within visualisations is showing in English. Specifically:

- [ ] Select data depending on the currency
- [ ] currencies in dropdown? Or are they same in all languages?
- [ ] Cumulative expenses
- [ ] Current filter: (x4)
- [ ] Total price
- [ ] Service used
- [ ] Day of week
- [ ] Begin trip address
- [ ] Values - Mon/Tue/Wed/Thur/Fri/Sat/Sun
- [ ] Values - Place names
- [ ] Values - COMPLETED and other Statuses
- [ ] All Column Headings of Table 
- [ ] General Information (in right panel)
- [ ] Orders (in right panel)
- [ ] Speed (in right panel)
- [ ] 'trips' (in right panel)
- [ ] 'mph' (in right panel)
- [ ] Total (in right panel)
- [ ] Average (in right panel)
- [ ] Miles, Min, Duration, Waiting Time, miles, min (in right panel)
- [ ] Reset all Filters (in right panel)

Under Trajets:
- [ ] In total there are 9 records of trips you have made with Uber
- [ ] (hover on the links or nodes to get more information
about the most frequent ones)
- [ ] Pickup places
- [ ] Dropoff places

Under Timeline:
(these seem to be globalised but no text being rendered for French, only language keys:

- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from 
- [ ] genericDateViewer.to 
- [ ] genericDateViewer.found
- [ ] genericDateViewer.dated-event

The rest are not globalised it seems:

- [ ] Filename, Date, Description (column headings)
- [ ] Values - Text within description field

On the Carte de Trajets

- [ ] Entire mapbox UI is rendered in English, country names, legend etc

Tab Name:

- [ ] Location Observations (tab name is in English)
- [ ] Title: Location Observations
- [ ] See all the location events in your files, corresponding to data that has been collected on you at or concerning a specific location.

Keys that need values for French:

- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] File, Latitude, Longitude, Description

**Comment by alexbfree** [comment]
For Twitter experience. 

- [ ] demo video is in English

**Comment by alexbfree** [comment]
see also related issue https://github.com/hestiaAI/hestialabs-experiences/issues/884

**Comment by valentinoli** [comment]
"Copyright" was left untouched on purpose, since it is commonly used in French

**Comment by pdehaye** [comment]
For Tinder:
- [ ] for the "Informations utilisateur.trice" all the field names are in English
- [ ] for "Likes and passes", there is a "swipes" and a "count" that appear
- [ ] in "comparaison" the selector only has choices in English
- [ ] for the correlation tab, the whole graph is in English

**Comment by alexbfree** [comment]
On all Filters:

- [ ] All text within popup filter messages and buttons, controls, etc. are in English.

**Comment by alexbfree** [comment]
On Netflix experience:

On Notifications tab:

- [ ] Settings/Filters (title of popup)
- [ ] Interacted with (2nd dropdown in popup) (Secondary non-language issues here - values are shown as 1 and 0 instead of Yes/No;Oui/Non)
- [ ] Device Model (3rd dropdown in popup)
- [ ] Reset, Close, save (buttons in popup)

**Comment by alexbfree** [comment]
Everywhere:

- [ ] 'sélectionnez une plage de temps pour effectuer un zoom'
needs capital letter at start (and possibly a bit of top padding, it is quite close to graph above)

**Comment by alexbfree** [comment]
Google Experience:

Endroits visités:

- [ ] When you click on a point on the map, title and all field labels are in English
- [ ] As mentioned above, general mapbox UI (inc country/city names etc) is in English. There is a language selector but it doesn't seem to include French, and doesn't seem to update the map, and bottom of dropdown is inaccessible (off bottom of map).
- [ ] column headings in table
- [ ] Place Visit Importance values in table (maybe Semantic Type too)

**Comment by alexbfree** [comment]
LinkedIn Experience:

Ciblage Publicitaire:

- [ ] label at start of each row, currently in English

Connections:

- [ ] Current filter (x4 graphs)
- [ ] Table column headings

General

- [ ] Timeline (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] genericDateViewer.graph-title,from,to,found,dated-event keys
- [ ] column headings File name, Date, Description

**Comment by alexbfree** [comment]
Facebook experience:

Interactions tab:

- [ ] column headings
- [ ] values in 'action' column
- [ ] (also note a non-language error here, timestamp is displayed raw/unformatted)

Interets supposes

- [ ] name (column title)
- [ ] the values themselves? (not sure if viable to translate)

General

- [ ] Timeline (tab name)
- [ ] Location observations (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] column headings in table
- [ ] Hierarchy within values within Description column

Location observations tab:
- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] title and fields of the popup when you click a point.
- [ ] mapbox UI in general, as mentioned elsewhere
- [ ] column headings

**Comment by alexbfree** [comment]
Issues in generic experience:

- [ ] Here's a summary of what we have found
- [ ] Analysed 3 files (522.02 kB) :
- [ ] 3 documents (maybe not translated, can't tell)

Observations de localisation

- [ ] All files are used (hover text on icon top right)

**Comment by alexbfree** [comment]
@andreaskundig @valentinoli 

All experiences now tested. this ticket can be worked on. Also raised along the way:

- #935 
- #936 
- #937 
-

**Comment by andreaskundig** [comment]
﻿I only had time to double-check facebook, twitter, instagram, twitter
﻿
- [ ] ﻿ChartViewTopRow.vue, settings icon -> Afficher "Others". Should we localize [key](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/components/chart/view/ChartViewTopRow.vue#L218) "Others"?
- [ ] Json explorer's [formatObject](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/utils/json.js#L170) and formatArray are not localized. One solution would be to take a translation function as argument.
- [ ] untranslated [ERROR](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/utils/utils.js#L41) in processError
- [ ] [BaseButtonShare.vue](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/components/base/button/BaseButtonShare.vue#L95)  has unlocalized texts 'Analyze the data collected on you',  'Your system does not support sharing files'
- [ ] The twitter:title and description configured in [nuxt.config.js](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/nuxt.config.js#L45). This is configured at build time. Take the default language from the config.
- [ ] The consent form is not localized yet, but not needed for our client now

- [ ] [ChartViewOverviewLinkedinConnection.vue](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/components/chart/view/ChartViewOverviewLinkedinConnection.vue#L6)
- [ ] [ChartViewListLinkedinInference.vue](https://github.com/hestiaAI/hestialabs-experiences/blob/a230afbacf798120d32c0e2af52921463ad52a14/experiences/components/chart/view/ChartViewListLinkedinInference.vue#L4)

**Comment by valentinoli** [comment]
[ ] - [ChartViewSankey.vue](https://github.com/hestiaAI/hestialabs-experiences/blob/f68b10ce2557adf85de1fe9cbff73ccae9543b0c/experiences/components/chart/view/ChartViewSankey.vue#L237-L241)

**Comment by alexbfree** [comment]
For testing:
- [ ] deploy to test site 
- [ ] test English.
- [ ] switch language on test site
- [ ] test French

**Comment by alexbfree** [comment]
@valentinoli to deploy, @alexbfree to test

**Comment by valentinoli** [comment]
@alexbfree 
Ready for testing.
Deployed on https://test.hestialabs.org

**Comment by alexbfree** [comment]
@andreaskundig @valentinoli can you provide any further information on how to test

- https://github.com/hestiaAI/hestialabs-experiences/issues/932#issuecomment-1242229237
- https://github.com/hestiaAI/hestialabs-experiences/issues/932#issuecomment-1252870465

**Comment by alexbfree** [comment]
Phew, here goes:

Testing checklist. -- French

## Uber

- [ ] Select data depending on the currency
- [ ] Cumulative expenses
- [ ] Current filter: (x4)
- [ ] Total price
- [ ] Service used
- [ ] Day of week
- [ ] Begin trip address
- [ ] Values - Mon/Tue/Wed/Thur/Fri/Sat/Sun
- [ ] All Column Headings of Table 
- [ ] General Information (in right panel)
- [ ] Orders (in right panel)
- [ ] Speed (in right panel)
- [ ] 'trips' (in right panel)
- [ ] 'mph' (in right panel)
- [ ] Total (in right panel)
- [ ] Average (in right panel)
- [ ] Miles, Min, Duration, Waiting Time, miles, min (in right panel)
- [ ] Reset all Filters (in right panel)

Under Trajets:
- [ ] In total there are 9 records of trips you have made with Uber
- [ ] (hover on the links or nodes to get more information
abo t the most frequent ones)
- [ ] Pickup places
- [ ] Dropoff places

Under Timeline:
(these seem to be globalised but no text being rendered for French, only language keys:

- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from 
- [ ] genericDateViewer.to 
- [ ] genericDateViewer.found
- [ ] genericDateViewer.dated-event

The rest are not globalised it seems:

- [ ] Filename, Date, Description (column headings)

On the Carte de Trajets

- [ ] Entire mapbox UI is rendered in English, country names, legend etc [I think we decided to skip this for now]

Tab Name:

- [ ] Location Observations (tab name is in English)
- [ ] Title: Location Observations
- [ ] See all the location events in your files, corresponding to data that has been collected on you at or concerning a specific location.

Keys that need values for French:

- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] File, Latitude, Longitude, Description

Other
- [ ] Timeline (name of tab)

----

## Twitter

For Twitter experience. 

- [ ] ~~demo video is in English~~ [in consultation with @fquellec we decided to keep it]

Under Vue d'ensemble des publicités:

- [ ] column headings are in English: Tweet ID, company, date, promoted tweet, engagement, targeting criteria
- [ ] On pie chart, it says Yes and No
- [ ] Engagement column, values say Yes and No

Under criteres de ciblages (tous):
- [ ] All values in the dropdown are in English

Under criteres de ciblages (1):
- [ ] Left panel: title
- [ ] Left panel: column headings
- [ ] in pie: Missing keys when you click each segment e.g. chart-view.sunburst.Binance


Under donnees supposees
- [ ] All titles
- [ ] All column headings
- [ ] Labels within 'General Information'

Timeline:
- [ ] Timeline (title)
- [ ] Files (name of dropdown)
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to 
- [ ] genericDateViewer.found 
- [ ] genericDateViewer.dated-event
- [ ] Filename, Date, Description (column headings)

Other 
- [ ] Timeline (tab name)
- [ ] Copyright (in footer and throughout all experiences) [the English word is also used in French]

----

## Tinder

- [ ] for the "Informations utilisateur.trice" all the field names are in English
- [ ] for "Likes and passes", there is a "swipes" and a "count" that appear
- [ ] in "comparaison" the selector only has choices in English
- [ ] in "comparaison" the hovers on the pie, and the title and date range at top, and legend, are all in english
- [ ] for the correlation tab, the whole graph is in English

-----

## Instagram


general:

- [ ] Timeline (Tab name) is English
- [ ] Likes (Tab names) is English [it's the same in French]
- [ ] Copyright statement (all pages) word in English [the English word is also used in French]

On Timeline tab:

- [ ] Timeline (title) in English
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to
- [ ] genericDateViewer.found
- [ ] genericDateViewer.datedevent
- [ ] Files (label of dropdown)
- [ ] + 96 others (in files dropdown)
- [ ] Column headings - File name, Date, Description
- [ ] All files are used (on pages icon hover)

On Vues tab:

- [ ] Current filter x 3 graphs
- [ ] Pie chart labels: Videos watched, posts viewed, ads viewed (note as well as no French, plural is missing in English too)
- [ ] All 13 consulté selected. Please click on the graph to apply filters. -> mixture of French and English!
- [ ] column headings Date, Name, Action
- [ ] column values in Action column

On Likes tab:

- [ ] Likes (title) [it's the same in French]
- [ ] Total likes (axis of top graph)
- [ ] Legend labels - posts liked, comments liked (top graph)
- [ ] Column headings - Date, Name, Action
- [ ] Values in Action column - Posts Liked, Comments Liked (note as well as no French, plural is missing in English too)

On Messages tab:

- [ ] Current filter (x4 graphs)
- [ ] Graph Titles - Messages Exchanged Over time, Top Users, Time of Day, Day
- [ ] Day Names - Mon, Tue, Wed, Thu, Fri, Sat, Sun (in bar graph under Day)
- [ ] All 105 messages selected. Please click on the graph to apply filters.
- [ ] Column titles - Sender, Message, Send At (Note this is wrong in English too, should be Sent at)

On Liste de suivi tab:
- [ ] 'followers' and 'followings' (in title and in graph legend
- [ ] Count (axis label)

----

## Netflix

On Netflix experience:

General:

- [ ] Timeline (tab name)

On Timeline tab:

- [ ] Files (label of dropdown)
- [ ] + 17 others (text within Files dropdown)
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to
- [ ] genericDateViewer.found
- [ ] genericDateViewer.dated-event

(By the way, the way this has been globalised is not best practice, as it relies on the word order remaining the same when you change language. Best practice is to use a string for the whole sentence, with variable substitution markers, this can support any word order across languages. Not an issue for English/French, but it is technical debt for later) 

- [ ] Column headings: File name, Date, Description
- [ ] All files are used (hover text top right icon)


On Notifications tab:

- [ ] Settings/Filters (title of popup)
- [ ] Interacted with (2nd dropdown in popup) (Secondary non-language issues here - values are shown as 1 and 0 instead of Yes/No;Oui/Non)
- [ ] Device Model (3rd dropdown in popup)
- [ ] Reset, Close, save (buttons in popup)

----

## All

- [ ] 'sélectionnez une plage de temps pour effectuer un zoom'
needs capital letter at start (and possibly a bit of top padding, it is quite close to graph above)

----

## Google

Google Experience:

Endroits visités:

- [ ] When you click on a point on the map, title and all field labels are in English
- [ ] column headings in table

Un Endroit Particulier:

- [ ] title and label when you click a point on map

Autres candidats:

- [ ] Column headings in table

Trajets:

- [ ] Column headings in table

Historique:

- *is showing blank tab for me*, can't tell if this is a data issue or code issue

wifi:

- *is showing blank tab for me*, can't tell if this is a data issue or code issue

----

## LinkedIn

Ciblage Publicitaire:

- [ ] label at start of each row, currently in English

Connections:

- [ ] Current filter (x4 graphs)
- [ ] Table column headings

General

- [ ] Timeline (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] genericDateViewer.graph-title,from,to,found,dated-event keys
- [ ] column headings File name, Date, Description

-----

## Facebook

Interactions tab:

- [ ] column headings
- [ ] (also note a non-language error here, timestamp is displayed raw/unformatted)

Interets supposes

- [ ] name (column title)

General

- [ ] Timeline (tab name)
- [ ] Location observations (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] column headings in table

Location observations tab:
- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] title and fields of the popup when you click a point.
- [ ] column headings

----

## Generic

- [ ] Here's a summary of what we have found
- [ ] Analysed 3 files (522.02 kB) :

Observations de localisation

- [ ] All files are used (hover text on icon top right)

----

# Testing checklist. -- ENGLISH

## Uber

- [ ] Select data depending on the currency
- [ ] Cumulative expenses
- [ ] Current filter: (x4)
- [ ] Total price
- [ ] Service used
- [ ] Day of week
- [ ] Begin trip address
- [ ] Values - Mon/Tue/Wed/Thur/Fri/Sat/Sun
- [ ] All Column Headings of Table 
- [ ] General Information (in right panel)
- [ ] Orders (in right panel)
- [ ] Speed (in right panel)
- [ ] 'trips' (in right panel)
- [ ] 'mph' (in right panel)
- [ ] Total (in right panel)
- [ ] Average (in right panel)
- [ ] Miles, Min, Duration, Waiting Time, miles, min (in right panel)
- [ ] Reset all Filters (in right panel)

Under Trajets:
- [ ] In total there are 9 records of trips you have made with Uber
- [ ] (hover on the links or nodes to get more information
abo t the most frequent ones)
- [ ] Pickup places
- [ ] Dropoff places

Under Timeline:
(these seem to be globalised but no text being rendered for French, only language keys:

- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from 
- [ ] genericDateViewer.to 
- [ ] genericDateViewer.found
- [ ] genericDateViewer.dated-event

The rest are not globalised it seems:

- [ ] Filename, Date, Description (column headings)

On the Carte de Trajets

- [ ] Entire mapbox UI is rendered in English, country names, legend etc [I think we decided to skip this for now]

Tab Name:

- [ ] Location Observations (tab name is in English)
- [ ] Title: Location Observations
- [ ] See all the location events in your files, corresponding to data that has been collected on you at or concerning a specific location.

Keys that need values for French:

- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] File, Latitude, Longitude, Description

Other
- [ ] Timeline (name of tab)

----

## Twitter

Under Vue d'ensemble des publicités:

- [ ] column headings are in English: Tweet ID, company, date, promoted tweet, engagement, targeting criteria
- [ ] On pie chart, it says Yes and No
- [ ] Engagement column, values say Yes and No

Under criteres de ciblages (tous):
- [ ] All values in the dropdown are in English

Under criteres de ciblages (1):
- [ ] Left panel: title
- [ ] Left panel: column headings
- [ ] in pie: Missing keys when you click each segment e.g. chart-view.sunburst.Binance


Under donnees supposees
- [ ] All titles
- [ ] All column headings
- [ ] Labels within 'General Information'

Timeline:
- [ ] Timeline (title)
- [ ] Files (name of dropdown)
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to 
- [ ] genericDateViewer.found 
- [ ] genericDateViewer.dated-event
- [ ] Filename, Date, Description (column headings)

Other 
- [ ] Timeline (tab name)
- [ ] Copyright (in footer and throughout all experiences) [the English word is also used in French]

----

## Tinder

- [ ] for the "Informations utilisateur.trice" all the field names are in English
- [ ] for "Likes and passes", there is a "swipes" and a "count" that appear
- [ ] in "comparaison" the selector only has choices in English
- [ ] in "comparaison" the hovers on the pie, and the title and date range at top, and legend, are all in english
- [ ] for the correlation tab, the whole graph is in English

-----

## Instagram


general:

- [ ] Timeline (Tab name) is English
- [ ] Likes (Tab names) is English [it's the same in French]
- [ ] Copyright statement (all pages) word in English [the English word is also used in French]

On Timeline tab:

- [ ] Timeline (title) in English
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to
- [ ] genericDateViewer.found
- [ ] genericDateViewer.datedevent
- [ ] Files (label of dropdown)
- [ ] + 96 others (in files dropdown)
- [ ] Column headings - File name, Date, Description
- [ ] All files are used (on pages icon hover)

On Vues tab:

- [ ] Current filter x 3 graphs
- [ ] Pie chart labels: Videos watched, posts viewed, ads viewed (note as well as no French, plural is missing in English too)
- [ ] All 13 consulté selected. Please click on the graph to apply filters. -> mixture of French and English!
- [ ] column headings Date, Name, Action
- [ ] column values in Action column

On Likes tab:

- [ ] Likes (title) [it's the same in French]
- [ ] Total likes (axis of top graph)
- [ ] Legend labels - posts liked, comments liked (top graph)
- [ ] Column headings - Date, Name, Action
- [ ] Values in Action column - Posts Liked, Comments Liked (note as well as no French, plural is missing in English too)

On Messages tab:

- [ ] Current filter (x4 graphs)
- [ ] Graph Titles - Messages Exchanged Over time, Top Users, Time of Day, Day
- [ ] Day Names - Mon, Tue, Wed, Thu, Fri, Sat, Sun (in bar graph under Day)
- [ ] All 105 messages selected. Please click on the graph to apply filters.
- [ ] Column titles - Sender, Message, Send At (Note this is wrong in English too, should be Sent at)

On Liste de suivi tab:
- [ ] 'followers' and 'followings' (in title and in graph legend
- [ ] Count (axis label)

----

## Netflix

On Netflix experience:

General:

- [ ] Timeline (tab name)

On Timeline tab:

- [ ] Files (label of dropdown)
- [ ] + 17 others (text within Files dropdown)
- [ ] genericDateViewer.graph-title
- [ ] genericDateViewer.from
- [ ] genericDateViewer.to
- [ ] genericDateViewer.found
- [ ] genericDateViewer.dated-event
- [ ] Column headings: File name, Date, Description
- [ ] All files are used (hover text top right icon)


On Notifications tab:

- [ ] Settings/Filters (title of popup)
- [ ] Interacted with (2nd dropdown in popup) (Secondary non-language issues here - values are shown as 1 and 0 instead of Yes/No;Oui/Non)
- [ ] Device Model (3rd dropdown in popup)
- [ ] Reset, Close, save (buttons in popup)

----

## All

- [ ] 'sélectionnez une plage de temps pour effectuer un zoom'
needs capital letter at start (and possibly a bit of top padding, it is quite close to graph above)

----

## Google

Google Experience:

Endroits visités:

- [ ] When you click on a point on the map, title and all field labels are in English
- [ ] column headings in table

Un Endroit Particulier:

- [ ] title and label when you click a point on map

Autres candidats:

- [ ] Column headings in table

Trajets:

- [ ] Column headings in table

Historique:

- *is showing blank tab for me*, can't tell if this is a data issue or code issue

wifi:

- *is showing blank tab for me*, can't tell if this is a data issue or code issue

----

## LinkedIn

Ciblage Publicitaire:

- [ ] label at start of each row, currently in English

Connections:

- [ ] Current filter (x4 graphs)
- [ ] Table column headings

General

- [ ] Timeline (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] genericDateViewer.graph-title,from,to,found,dated-event keys
- [ ] column headings File name, Date, Description

-----

## Facebook

Interactions tab:

- [ ] column headings
- [ ] (also note a non-language error here, timestamp is displayed raw/unformatted)

Interets supposes

- [ ] name (column title)

General

- [ ] Timeline (tab name)
- [ ] Location observations (tab name)

Timeline tab

- [ ] Timeline (title)
- [ ] See all the dated events in your files, corresponding to data that has been collected on you at or concerning a specific date.
- [ ] Files (label of dropdown)
- [ ] + n others (text in dropdown)
- [ ] column headings in table

Location observations tab:
- [ ] genericLocationViewer.graph-title
- [ ] genericLocationViewer.found
- [ ] genericLocationViewer.location
- [ ] title and fields of the popup when you click a point.
- [ ] column headings

----

## Generic

- [ ] Here's a summary of what we have found
- [ ] Analysed 3 files (522.02 kB) :

Observations de localisation

- [ ] All files are used (hover text on icon top right)

**Comment by alexbfree** [comment]
# Failed Tests

## French

### Uber

- [ ] All Column Headings of Table -> Distance column is still in English

**Comment by alexbfree** [comment]
I have done almost all of the tests, except two tabs on Facebook. I need a different Facebook data file that doesn't hit issue https://github.com/hestiaAI/hestialabs-experiences/issues/1042

Have requested new Facebook file in the hope that this was just a rare occurrence affecting one file.

**Comment by alexbfree** [comment]
since there are bugs that can be fixed, I will pass this back to Development needed.

See https://github.com/hestiaAI/hestialabs-experiences/issues/932#issuecomment-1260952166 for details of issues found.

@valentinoli may wish to comment, though it need not necessarily be Valentin who fixes the issues found.

**Comment by valentinoli** [comment]
Awaiting #1048 for test deployment

**Comment by valentinoli** [comment]
Deployed to test.hestialabs.org

**Comment by valentinoli** [comment]
Tests passed and closing
