### ISSUE TITLE
New course ( =bubble for now 😓) on digipower.academy

### ISSUE THREAD

**Issue by foucault-dumas** [hestiaAI/hestialabs-experiences#951]
New course:

Title: Socio-computational approaches to digital policy
Description: Use concepts and methods from the social sciences and humanities (SSH) to assess contemporary technological systems and the resulting socio-technical and political issues when used in the private and public spheres.

Experiences: uber, uber driver, tinder, her, twitter (possible to add others later after discussing with students)

Image: 
![image](https://user-images.githubusercontent.com/81250365/187158216-8a360cf4-61b4-4875-8e46-b5974f5cf6b5.png)

Thanks @fquellec

**Comment by foucault-dumas** [comment]
Concerning the "( =bubble for now 😓)", please read https://github.com/hestiaAI/clients/issues/3

**Comment by foucault-dumas** [comment]
@fquellec si tu push that, maybe you can also make this ultra small validated change to the homepage: https://github.com/hestiaAI/clients/issues/7

**Comment by fquellec** [comment]
Done
