### ISSUE TITLE
Move data samples from `experiences` to `packages`

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#985]
https://webpack.js.org/guides/asset-modules/

See examples of how we use asset modules for image files, SQL and Vega files:
https://github.com/hestiaAI/hestialabs-experiences/blob/ebe00dd62cd6f3453d7ce68d4dc418e313a17c83/packages/webpack.config.js#L47-L55

For data samples, you will want to emit them to a separate file and just export the URL with `asset-resource`

Say you have the data samples in a data-samples folder (in the lib/ directory for example). I think the following should then work for any file within that folder.

```js
// webpack.config.js
{
	test: /\/data-samples\//,
	type: 'asset/resource'
}
```

```js
// index.ts (of some package)
import dataSample from '@/data-samples/twitter.zip

const config = {
  ...
  dataSamples: [dataSample]
}
```

And the following lines in `nuxt.config.js` should be removed

https://github.com/hestiaAI/hestialabs-experiences/blob/ebe00dd62cd6f3453d7ce68d4dc418e313a17c83/experiences/nuxt.config.js#L213-L231

And the following lines in `UnitFiles.vue` are not needed anymore.

https://github.com/hestiaAI/hestialabs-experiences/blob/ebe00dd62cd6f3453d7ce68d4dc418e313a17c83/experiences/components/unit/files/UnitFiles.vue#L191-L200

**Comment by alexbfree** [comment]
@andreaskundig will review this as part of modularisation

**Comment by alexbfree** [comment]
@fquellec observed this is a prereq for modularisation

**Comment by valentinoli** [comment]
Deployed to test.hestialabs.org for testing

**Comment by valentinoli** [comment]
Tested and closing
